use top_5_futebol;
go
SET IDENTITY_INSERT gestao_futebol.jogo ON

EXEC gestao_futebol.CriaJogo 1,'Benfica','Vitoria de Guimaraes'
--team_home: 'Benfica'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 1, 42, 'Pedro Miguel Pereira'
EXEC gestao_futebol.CriaGolo 1, 48, 'Lisandro López'
EXEC gestao_futebol.CriaGolo 1, 9, 'Lisandro López'
EXEC gestao_futebol.CriaGolo 1, 41, 'João Miguel Coimbra Aurélio'
EXEC gestao_futebol.CriaGolo 1, 76, 'Jubal Rocha Mendes Junior'

EXEC gestao_futebol.CriaJogo 2,'Porto','Desportivo das Chaves'
--team_home: 'Porto'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 2, 52, 'Óliver Torres Muñoz'
EXEC gestao_futebol.CriaGolo 2, 62, 'Alberto Bueno Calvo'
EXEC gestao_futebol.CriaGolo 2, 67, 'Otávio Edmilson da Silva Monteiro'
EXEC gestao_futebol.CriaGolo 2, 73, 'Óliver Torres Muñoz'
EXEC gestao_futebol.CriaGolo 2, 30, 'Moussa Marega'

EXEC gestao_futebol.CriaJogo 3,'Vitoria de Setubal','Aves'
--team_home: 'Vitoria de Setubal'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 3, 31, 'Willyan Da Silva Barbosa'
EXEC gestao_futebol.CriaGolo 3, 36, 'Pedro José da Silva Trigueira'

EXEC gestao_futebol.CriaJogo 4,'Tondela','Belenenses'
--team_home: 'Tondela'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 4, 89, 'Alfredo Kulembe Ribeiro'

EXEC gestao_futebol.CriaJogo 5,'Feirense','Rio Ave'
--team_home: 'Feirense'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 5, 83, 'Bruno Andrade Toledo Nascimento'
EXEC gestao_futebol.CriaGolo 5, 89, 'Kódjo Alphonse'

EXEC gestao_futebol.CriaJogo 6,'Maritimo','Santa Clara'
--team_home: 'Maritimo'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 6, 56, 'Fabricio Santos de Jesus'

EXEC gestao_futebol.CriaJogo 7,'Moreirense','Sporting CP'
--team_home: 'Moreirense'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 7, 26, 'Ronaldo Peña'
EXEC gestao_futebol.CriaGolo 7, 12, 'Jacinto Muondo Dala'
EXEC gestao_futebol.CriaGolo 7, 65, 'João Maria Palhinha Gonçalves'
EXEC gestao_futebol.CriaGolo 7, 56, 'Bryan Ruíz'

EXEC gestao_futebol.CriaJogo 8,'Braga','Nacional'
--team_home: 'Braga'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 8, 66, 'João Carlos Vilaça Teixeira'
EXEC gestao_futebol.CriaGolo 8, 25, 'Ahmed Hassan'
EXEC gestao_futebol.CriaGolo 8, 52, 'Jefferson Nascimento'
EXEC gestao_futebol.CriaGolo 8, 84, 'João Paulo Dias Fernandes'
EXEC gestao_futebol.CriaGolo 8, 9, 'Diego Luiz Siqueira Medeiros'
EXEC gestao_futebol.CriaGolo 8, 86, 'Welthon Fiel Sampaio'

EXEC gestao_futebol.CriaJogo 9,'Portimonense','Boavista'
--team_home: 'Portimonense'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 9, 19, 'João Carlos Fonseca Silva'
EXEC gestao_futebol.CriaGolo 9, 22, 'Iván Bulos'

EXEC gestao_futebol.CriaJogo 10,'Aves','Tondela'
--team_home: 'Aves'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 10, 36, 'Paulo Ricardo de Jesús Machado'
EXEC gestao_futebol.CriaGolo 10, 43, 'Vanderley Dias Marinho'
EXEC gestao_futebol.CriaGolo 10, 71, 'Bruno André Freitas Monteiro'
EXEC gestao_futebol.CriaGolo 10, 79, 'Tyler Boyd'

EXEC gestao_futebol.CriaJogo 11,'Boavista','Benfica'
--team_home: 'Boavista'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 11, 74, 'João António Antunes Carvalho'
EXEC gestao_futebol.CriaGolo 11, 42, 'Haris Seferović'

EXEC gestao_futebol.CriaJogo 12,'Desportivo das Chaves','Portimonense'
--team_home: 'Desportivo das Chaves'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 12, 13, 'Nikola Maraš'
EXEC gestao_futebol.CriaGolo 12, 87, 'William Alves de Oliveira'

EXEC gestao_futebol.CriaJogo 13,'Sporting CP','Vitoria de Setubal'
--team_home: 'Sporting CP'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 13, 89, 'Rui Pedro dos Santos Patrício'
EXEC gestao_futebol.CriaGolo 13, 44, 'Bruno Miguel Borges Fernandes'
EXEC gestao_futebol.CriaGolo 13, 88, 'Luis Felipe Dias do Nascimento'

EXEC gestao_futebol.CriaJogo 14,'Belenenses','Porto'
--team_home: 'Belenenses'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 14, 83, 'Robert Åhman Persson'
EXEC gestao_futebol.CriaGolo 14, 77, 'Muriel Gustavo Becker'
EXEC gestao_futebol.CriaGolo 14, 47, 'Iker Casillas Fernández'
EXEC gestao_futebol.CriaGolo 14, 28, 'Óliver Torres Muñoz'
EXEC gestao_futebol.CriaGolo 14, 59, 'Óliver Torres Muñoz'

EXEC gestao_futebol.CriaJogo 15,'Nacional','Moreirense'
--team_home: 'Nacional'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 15, 22, 'Mário Jorge Quintas Felgueiras'
EXEC gestao_futebol.CriaGolo 15, 83, 'Iago Azevedo dos Santos'
EXEC gestao_futebol.CriaGolo 15, 9, 'Alfa Semedo Esteves'

EXEC gestao_futebol.CriaJogo 16,'Rio Ave','Maritimo'
--team_home: 'Rio Ave'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 16, 68, 'Victor Emanuel Araújo Ferreira'
EXEC gestao_futebol.CriaGolo 16, 19, 'José Lionn Barbosa de Lucena'
EXEC gestao_futebol.CriaGolo 16, 30, 'Nuno Miguel Gomes dos Santos'
EXEC gestao_futebol.CriaGolo 16, 69, 'Pedro Emanuel Ferreira Sousa'

EXEC gestao_futebol.CriaJogo 17,'Santa Clara','Braga'
--team_home: 'Santa Clara'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 17, 79, 'Abner Felipe Souza de Almeida'
EXEC gestao_futebol.CriaGolo 17, 30, 'Gonçalo Jardim Brandão'
EXEC gestao_futebol.CriaGolo 17, 29, 'José Filipe da Silva Moreira'
EXEC gestao_futebol.CriaGolo 17, 2, 'Nuno Miguel Jerónimo Sequeira'
EXEC gestao_futebol.CriaGolo 17, 40, 'Marko Bakić'
EXEC gestao_futebol.CriaGolo 17, 15, 'Ricardo Jorge da Luz Horta'

EXEC gestao_futebol.CriaJogo 18,'Vitoria de Guimaraes','Feirense'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 18, 2, 'Michał Miśkiewicz'

EXEC gestao_futebol.CriaJogo 19,'Maritimo','Desportivo das Chaves'
--team_home: 'Maritimo'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 19, 7, 'Fábio José Ferreira Pacheco'
EXEC gestao_futebol.CriaGolo 19, 47, 'Rodrigo Cunha Pereira de Pinho'
EXEC gestao_futebol.CriaGolo 19, 51, 'Emanuel Rodrigues Novo'

EXEC gestao_futebol.CriaJogo 20,'Benfica','Sporting CP'
--team_home: 'Benfica'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 20, 16, 'Luis Miguel Afonso Fernandes'
EXEC gestao_futebol.CriaGolo 20, 41, 'Bruno César Zanaki'

EXEC gestao_futebol.CriaJogo 21,'Portimonense','Santa Clara'
--team_home: 'Portimonense'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 21, 78, 'Felipe Francisco Macedo'
EXEC gestao_futebol.CriaGolo 21, 3, 'Pedro Miguel Cunha Sá'
EXEC gestao_futebol.CriaGolo 21, 60, 'Wesley Dias Dias Claudino'
EXEC gestao_futebol.CriaGolo 21, 62, 'Allano Brendon de Souza Lima'

EXEC gestao_futebol.CriaJogo 22,'Porto','Vitoria de Guimaraes'
--team_home: 'Porto'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 22, 74, 'João Paulo Santos da Costa'
EXEC gestao_futebol.CriaGolo 22, 86, 'Francisco Soares dos Santos'
EXEC gestao_futebol.CriaGolo 22, 51, 'Marcos André Costa Valente'
EXEC gestao_futebol.CriaGolo 22, 87, 'David Texeira'
EXEC gestao_futebol.CriaGolo 22, 56, 'David Texeira'

EXEC gestao_futebol.CriaJogo 23,'Feirense','Boavista'
--team_home: 'Feirense'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 23, 11, 'Bruno Andrade Toledo Nascimento'
EXEC gestao_futebol.CriaGolo 23, 24, 'Assis Giovanaz'

EXEC gestao_futebol.CriaJogo 24,'Vitoria de Setubal','Nacional'
--team_home: 'Vitoria de Setubal'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 24, 14, 'Sandro Rafael Veiga Cunha'
EXEC gestao_futebol.CriaGolo 24, 21, 'Pedro Filipe Barbosa Moreira'
EXEC gestao_futebol.CriaGolo 24, 85, 'Vasco André Moreira da Rocha'

EXEC gestao_futebol.CriaJogo 25,'Braga','Aves'
--team_home: 'Braga'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 25, 30, 'Dyego Wilverson Ferreira Sousa'
EXEC gestao_futebol.CriaGolo 25, 19, 'Ricardo José Araújo Ferreira'
EXEC gestao_futebol.CriaGolo 25, 12, 'Jefferson Nascimento'
EXEC gestao_futebol.CriaGolo 25, 89, 'Cristian Arango'

EXEC gestao_futebol.CriaJogo 26,'Tondela','Rio Ave'
--team_home: 'Tondela'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 26, 83, 'Pedro Nuno Fernandes Ferreira'
EXEC gestao_futebol.CriaGolo 26, 64, 'Cássio Albuquerque Anjos'

EXEC gestao_futebol.CriaJogo 27,'Moreirense','Belenenses'
--team_home: 'Moreirense'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 27, 40, 'Jhonatan Luiz Siqueira'
EXEC gestao_futebol.CriaGolo 27, 59, 'Juan Tomás Ortuño Martínez'

EXEC gestao_futebol.CriaJogo 28,'Desportivo das Chaves','Braga'
--team_home: 'Desportivo das Chaves'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 28, 79, 'Fransérgio Rodrigues Barbosa'

EXEC gestao_futebol.CriaJogo 29,'Vitoria de Guimaraes','Tondela'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 29, 43, 'Alexandre Costa Silva'

EXEC gestao_futebol.CriaJogo 30,'Belenenses','Vitoria de Setubal'
--team_home: 'Belenenses'  team_away: 'Vitoria de Setubal' 

EXEC gestao_futebol.CriaJogo 31,'Santa Clara','Boavista'
--team_home: 'Santa Clara'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 31, 61, 'José Filipe da Silva Moreira'
EXEC gestao_futebol.CriaGolo 31, 73, 'Wesley Dias Dias Claudino'
EXEC gestao_futebol.CriaGolo 31, 51, 'Thierry Ramos Graça'
EXEC gestao_futebol.CriaGolo 31, 51, 'Duarte Beirão Valente'
EXEC gestao_futebol.CriaGolo 31, 52, 'Raphael Rossi Branco'
EXEC gestao_futebol.CriaGolo 31, 66, 'Aymen Tahar'

EXEC gestao_futebol.CriaJogo 32,'Sporting CP','Feirense'
--team_home: 'Sporting CP'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 32, 88, 'João Maria Palhinha Gonçalves'

EXEC gestao_futebol.CriaJogo 33,'Aves','Maritimo'
--team_home: 'Aves'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 33, 73, 'Pablo Renan dos Santos'

EXEC gestao_futebol.CriaJogo 34,'Nacional','Benfica'
--team_home: 'Nacional'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 34, 53, 'Filipe Augusto Carvalho Souza'
EXEC gestao_futebol.CriaGolo 34, 0, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 34, 65, 'Paulo Jorge Pedro Lopes'
EXEC gestao_futebol.CriaGolo 34, 21, 'Jonas Gonçalves Oliveira'

EXEC gestao_futebol.CriaJogo 35,'Porto','Moreirense'
--team_home: 'Porto'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 35, 38, 'Alex Nicolao Telles'
EXEC gestao_futebol.CriaGolo 35, 18, 'Francisco Soares dos Santos'
EXEC gestao_futebol.CriaGolo 35, 74, 'Fabiano Ribeiro de Freitas'

EXEC gestao_futebol.CriaJogo 36,'Rio Ave','Portimonense'
--team_home: 'Rio Ave'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 36, 31, 'Yazalde Gomes Pinto'
EXEC gestao_futebol.CriaGolo 36, 44, 'Nélson Macedo Monte'
EXEC gestao_futebol.CriaGolo 36, 47, 'Ricardo Jorge Rodrigues Pessoa'

EXEC gestao_futebol.CriaJogo 37,'Boavista','Desportivo das Chaves'
--team_home: 'Boavista'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 37, 76, 'Jaílton Alves Miranda'
EXEC gestao_futebol.CriaGolo 37, 39, 'Jefferson De Jesus Santos'
EXEC gestao_futebol.CriaGolo 37, 0, 'Nuno André da Silva Coelho'

EXEC gestao_futebol.CriaJogo 38,'Maritimo','Belenenses'
--team_home: 'Maritimo'  team_away: 'Belenenses' 

EXEC gestao_futebol.CriaJogo 39,'Santa Clara','Rio Ave'
--team_home: 'Santa Clara'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 39, 15, 'Luís Carlos Santos Ribeiro'
EXEC gestao_futebol.CriaGolo 39, 47, 'Anastasios Karamanos'
EXEC gestao_futebol.CriaGolo 39, 6, 'Eliseu Mendja Soares Cassamá'
EXEC gestao_futebol.CriaGolo 39, 83, 'Leandro de Lima Silva'

EXEC gestao_futebol.CriaJogo 40,'Vitoria de Setubal','Porto'
--team_home: 'Vitoria de Setubal'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 40, 24, 'José Diogo Dalot Teixeira'
EXEC gestao_futebol.CriaGolo 40, 61, 'Alex Nicolao Telles'

EXEC gestao_futebol.CriaJogo 41,'Benfica','Aves'
--team_home: 'Benfica'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 41, 15, 'Alejandro Grimaldo García'
EXEC gestao_futebol.CriaGolo 41, 46, 'Pedro Miguel Pereira'

EXEC gestao_futebol.CriaJogo 42,'Feirense','Nacional'
--team_home: 'Feirense'  team_away: 'Nacional' 

EXEC gestao_futebol.CriaJogo 43,'Portimonense','Vitoria de Guimaraes'
--team_home: 'Portimonense'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 43, 84, 'Ricardo Jorge Rodrigues Pessoa'
EXEC gestao_futebol.CriaGolo 43, 22, 'Paulo Henrique Soares dos Santos'
EXEC gestao_futebol.CriaGolo 43, 7, 'Chidera Ezeh'
EXEC gestao_futebol.CriaGolo 43, 4, 'Hélder José Castro Ferreira'
EXEC gestao_futebol.CriaGolo 43, 10, 'Miguel Ângelo Moreira Magalhães'

EXEC gestao_futebol.CriaJogo 44,'Tondela','Moreirense'
--team_home: 'Tondela'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 44, 14, 'Hélder Luís Vieira Tavares'
EXEC gestao_futebol.CriaGolo 44, 75, 'Rafael Leme Amorim'

EXEC gestao_futebol.CriaJogo 45,'Braga','Sporting CP'
--team_home: 'Braga'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 45, 18, 'João Carlos Vilaça Teixeira'

EXEC gestao_futebol.CriaJogo 46,'Desportivo das Chaves','Benfica'
--team_home: 'Desportivo das Chaves'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 46, 50, 'Jorge Fernando Barbosa Intima'
EXEC gestao_futebol.CriaGolo 46, 9, 'Pedro Miguel Pereira Silva'
EXEC gestao_futebol.CriaGolo 46, 17, 'Rúben Alves Dias'
EXEC gestao_futebol.CriaGolo 46, 31, 'Eduardo Salvio'

EXEC gestao_futebol.CriaJogo 47,'Porto','Tondela'
--team_home: 'Porto'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 47, 32, 'Iván Marcano Sierra'

EXEC gestao_futebol.CriaJogo 48,'Moreirense','Feirense'
--team_home: 'Moreirense'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 48, 56, 'Alfa Semedo Esteves'

EXEC gestao_futebol.CriaJogo 49,'Rio Ave','Boavista'
--team_home: 'Rio Ave'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 49, 81, 'Ricardo José Monteiro'
EXEC gestao_futebol.CriaGolo 49, 14, 'Ricardo José Monteiro'
EXEC gestao_futebol.CriaGolo 49, 69, 'Jaílton Alves Miranda'

EXEC gestao_futebol.CriaJogo 50,'Sporting CP','Maritimo'
--team_home: 'Sporting CP'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 50, 6, 'Jonathan Silva'
EXEC gestao_futebol.CriaGolo 50, 3, 'Bruno César Zanaki'

EXEC gestao_futebol.CriaJogo 51,'Belenenses','Braga'
--team_home: 'Belenenses'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 51, 33, 'Ricardo Jorge da Luz Horta'
EXEC gestao_futebol.CriaGolo 51, 9, 'Raúl Michel Melo da Silva'
EXEC gestao_futebol.CriaGolo 51, 44, 'Joan Angel Román Ollè'

EXEC gestao_futebol.CriaJogo 52,'Vitoria de Guimaraes','Vitoria de Setubal'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 52, 37, 'Óscar Estupiñán'
EXEC gestao_futebol.CriaGolo 52, 67, 'Diogo Leite de Sousa'

EXEC gestao_futebol.CriaJogo 53,'Nacional','Santa Clara'
--team_home: 'Nacional'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 53, 54, 'Gustavo H. Barbosa Freire'
EXEC gestao_futebol.CriaGolo 53, 69, 'Bruno Gomes Oliveira Conceição'
EXEC gestao_futebol.CriaGolo 53, 54, 'Abner Felipe Souza de Almeida'

EXEC gestao_futebol.CriaJogo 54,'Aves','Portimonense'
--team_home: 'Aves'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 54, 36, 'Vitor Hugo Gomes da Silva'
EXEC gestao_futebol.CriaGolo 54, 64, 'Vanderley Dias Marinho'
EXEC gestao_futebol.CriaGolo 54, 84, 'Amilton Minervino da Silva'

EXEC gestao_futebol.CriaJogo 55,'Feirense','Belenenses'
--team_home: 'Feirense'  team_away: 'Belenenses' 

EXEC gestao_futebol.CriaJogo 56,'Santa Clara','Desportivo das Chaves'
--team_home: 'Santa Clara'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 56, 52, 'Pedro Filipe Rodrigues'

EXEC gestao_futebol.CriaJogo 57,'Tondela','Nacional'
--team_home: 'Tondela'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 57, 31, 'Rafael Leme Amorim'
EXEC gestao_futebol.CriaGolo 57, 51, 'Luís Miguel Vieira da Silva'

EXEC gestao_futebol.CriaJogo 58,'Maritimo','Vitoria de Guimaraes'
--team_home: 'Maritimo'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 58, 64, 'Charles Marcelo da Silva'
EXEC gestao_futebol.CriaGolo 58, 56, 'Ghislain Konan'
EXEC gestao_futebol.CriaGolo 58, 51, 'Sueliton Florêncio Nogueira'
EXEC gestao_futebol.CriaGolo 58, 67, 'David Texeira'

EXEC gestao_futebol.CriaJogo 59,'Vitoria de Setubal','Moreirense'
--team_home: 'Vitoria de Setubal'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 59, 60, 'Tomás Martins Podstawski'
EXEC gestao_futebol.CriaGolo 59, 63, 'André Alexandre Antunes Pedrosa'
EXEC gestao_futebol.CriaGolo 59, 5, 'Nuno Miguel Sousa Pinto'

EXEC gestao_futebol.CriaJogo 60,'Braga','Rio Ave'
--team_home: 'Braga'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 60, 84, 'Robert Murić'
EXEC gestao_futebol.CriaGolo 60, 13, 'Marcos Nascimento Teixeira'

EXEC gestao_futebol.CriaJogo 61,'Benfica','Porto'
--team_home: 'Benfica'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 61, 79, 'Jardel Nivaldo Vieira'

EXEC gestao_futebol.CriaJogo 62,'Boavista','Aves'
--team_home: 'Boavista'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 62, 25, 'Tiago Manuel Oliveira Mesquita'

EXEC gestao_futebol.CriaJogo 63,'Portimonense','Sporting CP'
--team_home: 'Portimonense'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 63, 15, 'Pedro Miguel Cunha Sá'
EXEC gestao_futebol.CriaGolo 63, 73, 'Pedro Miguel Cunha Sá'
EXEC gestao_futebol.CriaGolo 63, 71, 'Lumor Agbenyenu'
EXEC gestao_futebol.CriaGolo 63, 46, 'Stanley Awurum'
EXEC gestao_futebol.CriaGolo 63, 50, 'Stefan Ristovski'
EXEC gestao_futebol.CriaGolo 63, 42, 'Rui Pedro dos Santos Patrício'

EXEC gestao_futebol.CriaJogo 64,'Vitoria de Guimaraes','Braga'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 64, 15, 'Alhassan Wakaso'
EXEC gestao_futebol.CriaGolo 64, 33, 'Marcelo Augusto Ferreira Teixeira'

EXEC gestao_futebol.CriaJogo 65,'Nacional','Portimonense'
--team_home: 'Nacional'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 65, 8, 'Bruno Vinícius Souza Ramos'

EXEC gestao_futebol.CriaJogo 66,'Aves','Santa Clara'
--team_home: 'Aves'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 66, 34, 'Cláudio Falcão Santos'
EXEC gestao_futebol.CriaGolo 66, 87, 'Pedro Filipe Tinoco Monteiro'
EXEC gestao_futebol.CriaGolo 66, 46, 'Bruno Gomes Oliveira Conceição'

EXEC gestao_futebol.CriaJogo 67,'Belenenses','Benfica'
--team_home: 'Belenenses'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 67, 75, 'Hassan Yebda'
EXEC gestao_futebol.CriaGolo 67, 51, 'Maurides Roque Junior'

EXEC gestao_futebol.CriaJogo 68,'Rio Ave','Desportivo das Chaves'
--team_home: 'Rio Ave'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 68, 5, 'Sunday Abalo'

EXEC gestao_futebol.CriaJogo 69,'Moreirense','Maritimo'
--team_home: 'Moreirense'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 69, 78, 'Frédéric Ferreira Maciel'

EXEC gestao_futebol.CriaJogo 70,'Porto','Feirense'
--team_home: 'Porto'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 70, 1, 'Hernâni Jorge Santos Fortes'
EXEC gestao_futebol.CriaGolo 70, 84, 'Vincent Aboubakar'

EXEC gestao_futebol.CriaJogo 71,'Sporting CP','Boavista'
--team_home: 'Sporting CP'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 71, 11, 'Radosav Petrović'
EXEC gestao_futebol.CriaGolo 71, 70, 'Douglas Franco Teixeira'
EXEC gestao_futebol.CriaGolo 71, 31, 'Rui Pedro dos Santos Patrício'

EXEC gestao_futebol.CriaJogo 72,'Tondela','Vitoria de Setubal'
--team_home: 'Tondela'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 72, 43, 'Cláudio Pires de Morais Ramos'
EXEC gestao_futebol.CriaGolo 72, 4, 'João José Pereira da Costa'
EXEC gestao_futebol.CriaGolo 72, 33, 'Vasco Herculano Cunha Fernandes'

EXEC gestao_futebol.CriaJogo 73,'Benfica','Moreirense'
--team_home: 'Benfica'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 73, 8, 'Haris Seferović'
EXEC gestao_futebol.CriaGolo 73, 89, 'Alfa Semedo Esteves'
EXEC gestao_futebol.CriaGolo 73, 29, 'Ângelo Pelegrinelli Neto'
EXEC gestao_futebol.CriaGolo 73, 72, 'Hichem Belkaroui'

EXEC gestao_futebol.CriaJogo 74,'Boavista','Vitoria de Guimaraes'
--team_home: 'Boavista'  team_away: 'Vitoria de Guimaraes' 

EXEC gestao_futebol.CriaJogo 75,'Maritimo','Porto'
--team_home: 'Maritimo'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 75, 86, 'Alberto Bueno Calvo'
EXEC gestao_futebol.CriaGolo 75, 35, 'Alex Nicolao Telles'

EXEC gestao_futebol.CriaJogo 76,'Portimonense','Belenenses'
--team_home: 'Portimonense'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 76, 69, 'Theodoros Ryuki Panagopoulos'
EXEC gestao_futebol.CriaGolo 76, 5, 'André Geraldes de Barros'

EXEC gestao_futebol.CriaJogo 77,'Feirense','Tondela'
--team_home: 'Feirense'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 77, 88, 'Luis Henrique Farinhas Taffner'
EXEC gestao_futebol.CriaGolo 77, 11, 'Elvis Manuel Monteiro Macedo'
EXEC gestao_futebol.CriaGolo 77, 56, 'João Carlos Reis Graça'
EXEC gestao_futebol.CriaGolo 77, 22, 'Junior Pius'
EXEC gestao_futebol.CriaGolo 77, 14, 'Murilo Oliveira de Freitas'
EXEC gestao_futebol.CriaGolo 77, 61, 'Bruno André Freitas Monteiro'

EXEC gestao_futebol.CriaJogo 78,'Santa Clara','Sporting CP'
--team_home: 'Santa Clara'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 78, 23, 'Wesley Dias Dias Claudino'
EXEC gestao_futebol.CriaGolo 78, 7, 'Wallyson Teixeira Mallmann'
EXEC gestao_futebol.CriaGolo 78, 29, 'Rui Pedro dos Santos Patrício'

EXEC gestao_futebol.CriaJogo 79,'Braga','Vitoria de Setubal'
--team_home: 'Braga'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 79, 38, 'Jefferson Nascimento'
EXEC gestao_futebol.CriaGolo 79, 89, 'André Filipe Luz Horta'
EXEC gestao_futebol.CriaGolo 79, 19, 'Vasco Herculano Cunha Fernandes'

EXEC gestao_futebol.CriaJogo 80,'Desportivo das Chaves','Aves'
--team_home: 'Desportivo das Chaves'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 80, 69, 'Paulo Sérgio Mota'
EXEC gestao_futebol.CriaGolo 80, 35, 'Cristian Arango'
EXEC gestao_futebol.CriaGolo 80, 21, 'Alexandre Garcia Guedes'

EXEC gestao_futebol.CriaJogo 81,'Rio Ave','Nacional'
--team_home: 'Rio Ave'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 81, 18, 'Hélder Tiago Pinto Moura Guedes'
EXEC gestao_futebol.CriaGolo 81, 40, 'Silvério Júnio Gonçalves da Silva'
EXEC gestao_futebol.CriaGolo 81, 48, 'Gabriel Airton de Souza'
EXEC gestao_futebol.CriaGolo 81, 44, 'André Manuel Nogueira Sousa'
EXEC gestao_futebol.CriaGolo 81, 34, 'Welthon Fiel Sampaio'
EXEC gestao_futebol.CriaGolo 81, 29, 'André Filipe Carneiro Leal'

EXEC gestao_futebol.CriaJogo 82,'Moreirense','Portimonense'
--team_home: 'Moreirense'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 82, 38, 'Ença Fati'
EXEC gestao_futebol.CriaGolo 82, 81, 'Nuno Alberto Macedo Pereira'

EXEC gestao_futebol.CriaJogo 83,'Vitoria de Setubal','Feirense'
--team_home: 'Vitoria de Setubal'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 83, 57, 'Nuno Miguel Sousa Pinto'
EXEC gestao_futebol.CriaGolo 83, 79, 'Gonçalo Mendes Paciência'
EXEC gestao_futebol.CriaGolo 83, 33, 'José Pedro Costa Leite'

EXEC gestao_futebol.CriaJogo 84,'Aves','Rio Ave'
--team_home: 'Aves'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 84, 57, 'Cláudio Falcão Santos'
EXEC gestao_futebol.CriaGolo 84, 7, 'Rodrigo Alves Soares'
EXEC gestao_futebol.CriaGolo 84, 19, 'Pedro Manuel da Silva Moreira'

EXEC gestao_futebol.CriaJogo 85,'Belenenses','Boavista'
--team_home: 'Belenenses'  team_away: 'Boavista' 

EXEC gestao_futebol.CriaJogo 86,'Nacional','Maritimo'
--team_home: 'Nacional'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 86, 14, 'Ricardo Jorge Pinto da Silva'

EXEC gestao_futebol.CriaJogo 87,'Porto','Braga'
--team_home: 'Porto'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 87, 85, 'Wenderson Nascimento Galeno'

EXEC gestao_futebol.CriaJogo 88,'Vitoria de Guimaraes','Santa Clara'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 88, 25, 'João Miguel Coimbra Aurélio'
EXEC gestao_futebol.CriaGolo 88, 78, 'Dénis Paulo Duarte'

EXEC gestao_futebol.CriaJogo 89,'Sporting CP','Desportivo das Chaves'
--team_home: 'Sporting CP'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 89, 46, 'Rodrigo Battaglia'
EXEC gestao_futebol.CriaGolo 89, 81, 'Cristiano Piccini'
EXEC gestao_futebol.CriaGolo 89, 58, 'Ricardo Jorge Novo Nunes'

EXEC gestao_futebol.CriaJogo 90,'Tondela','Benfica'
--team_home: 'Tondela'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 90, 49, 'Mateusz Zachara'
EXEC gestao_futebol.CriaGolo 90, 25, 'Martin Chrien'
EXEC gestao_futebol.CriaGolo 90, 24, 'Pedro Miguel Pereira'
EXEC gestao_futebol.CriaGolo 90, 19, 'Andreas Samaris'

EXEC gestao_futebol.CriaJogo 91,'Santa Clara','Belenenses'
--team_home: 'Santa Clara'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 91, 65, 'Lucas E. Santana de Oliveira'
EXEC gestao_futebol.CriaGolo 91, 21, 'Victor Andrade Santos'
EXEC gestao_futebol.CriaGolo 91, 32, 'Jesús Hernández'
EXEC gestao_futebol.CriaGolo 91, 57, 'Ronei Gleison Rodrigues Reis'
EXEC gestao_futebol.CriaGolo 91, 40, 'Merlin Tandjigora'

EXEC gestao_futebol.CriaJogo 92,'Benfica','Feirense'
--team_home: 'Benfica'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 92, 26, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 92, 34, 'Eduardo Salvio'
EXEC gestao_futebol.CriaGolo 92, 37, 'Mile Svilar'
EXEC gestao_futebol.CriaGolo 92, 50, 'Filip Krovinović'

EXEC gestao_futebol.CriaJogo 93,'Maritimo','Vitoria de Setubal'
--team_home: 'Maritimo'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 93, 72, 'João Pedro Reis Amaral'

EXEC gestao_futebol.CriaJogo 94,'Braga','Moreirense'
--team_home: 'Braga'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 94, 47, 'Bruno Ricardo Valdez Wilson'
EXEC gestao_futebol.CriaGolo 94, 33, 'Marcelo Augusto Ferreira Teixeira'

EXEC gestao_futebol.CriaJogo 95,'Aves','Nacional'
--team_home: 'Aves'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 95, 58, 'Adriano Facchini'
EXEC gestao_futebol.CriaGolo 95, 59, 'Salvador José Milhazes Agra'
EXEC gestao_futebol.CriaGolo 95, 16, 'André Filipe Ribeiro Leão'
EXEC gestao_futebol.CriaGolo 95, 8, 'André Filipe Ribeiro Leão'
EXEC gestao_futebol.CriaGolo 95, 6, 'Diego Luiz Siqueira Medeiros'

EXEC gestao_futebol.CriaJogo 96,'Boavista','Porto'
--team_home: 'Boavista'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 96, 56, 'Diogo Lucas Queirós'

EXEC gestao_futebol.CriaJogo 97,'Desportivo das Chaves','Vitoria de Guimaraes'
--team_home: 'Desportivo das Chaves'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 97, 35, 'Francisco Simões Rodrigues'

EXEC gestao_futebol.CriaJogo 98,'Portimonense','Tondela'
--team_home: 'Portimonense'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 98, 82, 'Paulo Henrique Soares dos Santos'
EXEC gestao_futebol.CriaGolo 98, 34, 'Emmanuel Hackman'
EXEC gestao_futebol.CriaGolo 98, 48, 'Bruno Vinícius Souza Ramos'
EXEC gestao_futebol.CriaGolo 98, 40, 'Miguel Filipe Nunes Cardoso'
EXEC gestao_futebol.CriaGolo 98, 50, 'Pedro Nuno Fernandes Ferreira'

EXEC gestao_futebol.CriaJogo 99,'Rio Ave','Sporting CP'
--team_home: 'Rio Ave'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 99, 43, 'José Lionn Barbosa de Lucena'
EXEC gestao_futebol.CriaGolo 99, 88, 'Tobias Pereira Figueiredo'
EXEC gestao_futebol.CriaGolo 99, 61, 'Iuri José Picanço Medeiros'
EXEC gestao_futebol.CriaGolo 99, 13, 'Cristiano Piccini'

EXEC gestao_futebol.CriaJogo 100,'Porto','Portimonense'
--team_home: 'Porto'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 100, 36, 'Iker Casillas Fernández'
EXEC gestao_futebol.CriaGolo 100, 42, 'Fabiano Ribeiro de Freitas'
EXEC gestao_futebol.CriaGolo 100, 89, 'Diogo Filipe Pinto Leite'
EXEC gestao_futebol.CriaGolo 100, 71, 'André Filipe Brás André'
EXEC gestao_futebol.CriaGolo 100, 61, 'Stanley Awurum'

EXEC gestao_futebol.CriaJogo 101,'Belenenses','Desportivo das Chaves'
--team_home: 'Belenenses'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 101, 49, 'Jesús Hernández'

EXEC gestao_futebol.CriaJogo 102,'Vitoria de Setubal','Benfica'
--team_home: 'Vitoria de Setubal'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 102, 41, 'Douglas Pereira dos Santos'

EXEC gestao_futebol.CriaJogo 103,'Tondela','Braga'
--team_home: 'Tondela'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 103, 69, 'André Filipe Luz Horta'

EXEC gestao_futebol.CriaJogo 104,'Vitoria de Guimaraes','Rio Ave'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 104, 33, 'Miguel Ângelo Moreira Magalhães'
EXEC gestao_futebol.CriaGolo 104, 53, 'Raphael Dias Belloli'
EXEC gestao_futebol.CriaGolo 104, 35, 'Miguel Ângelo Moreira Magalhães'
EXEC gestao_futebol.CriaGolo 104, 21, 'Hélder Tiago Pinto Moura Guedes'
EXEC gestao_futebol.CriaGolo 104, 53, 'Yuri Oliveira Ribeiro'

EXEC gestao_futebol.CriaJogo 105,'Moreirense','Santa Clara'
--team_home: 'Moreirense'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 105, 43, 'Duarte Beirão Valente'

EXEC gestao_futebol.CriaJogo 106,'Nacional','Boavista'
--team_home: 'Nacional'  team_away: 'Boavista' 

EXEC gestao_futebol.CriaJogo 107,'Sporting CP','Aves'
--team_home: 'Sporting CP'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 107, 68, 'Bryan Ruíz'
EXEC gestao_futebol.CriaGolo 107, 50, 'Douglas Franco Teixeira'
EXEC gestao_futebol.CriaGolo 107, 20, 'André Almeida Pinto'
EXEC gestao_futebol.CriaGolo 107, 73, 'Wallyson Teixeira Mallmann'
EXEC gestao_futebol.CriaGolo 107, 65, 'Diego Fortunato dos Santos Queiroz'

EXEC gestao_futebol.CriaJogo 108,'Feirense','Maritimo'
--team_home: 'Feirense'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 108, 42, 'Dele Alampasu'
EXEC gestao_futebol.CriaGolo 108, 62, 'Filipe Santos Oliveira'

EXEC gestao_futebol.CriaJogo 109,'Portimonense','Vitoria de Setubal'
--team_home: 'Portimonense'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 109, 84, 'Emmanuel Hackman'
EXEC gestao_futebol.CriaGolo 109, 63, 'Inácio Carneiro dos Santos'
EXEC gestao_futebol.CriaGolo 109, 51, 'Carlos Anastácio Henriques'
EXEC gestao_futebol.CriaGolo 109, 18, 'Willyan Da Silva Barbosa'

EXEC gestao_futebol.CriaJogo 110,'Braga','Feirense'
--team_home: 'Braga'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 110, 29, 'Raúl Michel Melo da Silva'
EXEC gestao_futebol.CriaGolo 110, 57, 'Marko Bakić'
EXEC gestao_futebol.CriaGolo 110, 1, 'Marcelo Augusto Ferreira Teixeira'
EXEC gestao_futebol.CriaGolo 110, 71, 'Marcelo Augusto Ferreira Teixeira'

EXEC gestao_futebol.CriaJogo 111,'Aves','Vitoria de Guimaraes'
--team_home: 'Aves'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 111, 1, 'Luis Fariña'
EXEC gestao_futebol.CriaGolo 111, 53, 'Hélder José Castro Ferreira'

EXEC gestao_futebol.CriaJogo 112,'Boavista','Tondela'
--team_home: 'Boavista'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 112, 57, 'Leonardo Ruíz'
EXEC gestao_futebol.CriaGolo 112, 53, 'Diogo Guedes Nunes'

EXEC gestao_futebol.CriaJogo 113,'Desportivo das Chaves','Moreirense'
--team_home: 'Desportivo das Chaves'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 113, 24, 'Domingos Sousa Menezes Duarte'
EXEC gestao_futebol.CriaGolo 113, 79, 'Alfa Semedo Esteves'
EXEC gestao_futebol.CriaGolo 113, 20, 'Koffi Kouao'

EXEC gestao_futebol.CriaJogo 114,'Santa Clara','Porto'
--team_home: 'Santa Clara'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 114, 19, 'Luís Carlos Santos Ribeiro'
EXEC gestao_futebol.CriaGolo 114, 63, 'Diogo Filipe Pinto Leite'
EXEC gestao_futebol.CriaGolo 114, 53, 'Francisco Soares dos Santos'

EXEC gestao_futebol.CriaJogo 115,'Maritimo','Benfica'
--team_home: 'Maritimo'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 115, 75, 'Raúl Jiménez'

EXEC gestao_futebol.CriaJogo 116,'Rio Ave','Belenenses'
--team_home: 'Rio Ave'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 116, 46, 'Eliseu Mendja Soares Cassamá'
EXEC gestao_futebol.CriaGolo 116, 66, 'João Pedro Barradas Novais'
EXEC gestao_futebol.CriaGolo 116, 23, 'Bernardo Oliveira Dias'
EXEC gestao_futebol.CriaGolo 116, 19, 'Merlin Tandjigora'

EXEC gestao_futebol.CriaJogo 117,'Sporting CP','Nacional'
--team_home: 'Sporting CP'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 117, 71, 'Alan Ruiz'
EXEC gestao_futebol.CriaGolo 117, 49, 'Manuel David Afonso'
EXEC gestao_futebol.CriaGolo 117, 39, 'Radosav Petrović'
EXEC gestao_futebol.CriaGolo 117, 59, 'Bruno César Zanaki'
EXEC gestao_futebol.CriaGolo 117, 37, 'Bruno Miguel Borges Fernandes'
EXEC gestao_futebol.CriaGolo 117, 42, 'Pedro Pinho Marques'
EXEC gestao_futebol.CriaGolo 117, 55, 'Luiz Phellype Luciano Silva'

EXEC gestao_futebol.CriaJogo 118,'Belenenses','Aves'
--team_home: 'Belenenses'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 118, 6, 'André Geraldes de Barros'
EXEC gestao_futebol.CriaGolo 118, 70, 'Florent Hanin'
EXEC gestao_futebol.CriaGolo 118, 69, 'Hassan Yebda'
EXEC gestao_futebol.CriaGolo 118, 28, 'Bakary Saré'
EXEC gestao_futebol.CriaGolo 118, 77, 'Vincent Sasso'
EXEC gestao_futebol.CriaGolo 118, 9, 'Vitor Hugo Gomes da Silva'
EXEC gestao_futebol.CriaGolo 118, 12, 'Paulo Ricardo de Jesús Machado'

EXEC gestao_futebol.CriaJogo 119,'Feirense','Portimonense'
--team_home: 'Feirense'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 119, 33, 'Fabrício dos Santos Messias'

EXEC gestao_futebol.CriaJogo 120,'Moreirense','Boavista'
--team_home: 'Moreirense'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 120, 24, 'Ousmane Dramé'
EXEC gestao_futebol.CriaGolo 120, 56, 'Giorgi Makaridze'
EXEC gestao_futebol.CriaGolo 120, 7, 'Leonardo Ruíz'

EXEC gestao_futebol.CriaJogo 121,'Vitoria de Setubal','Santa Clara'
--team_home: 'Vitoria de Setubal'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 121, 61, 'Lucas Silva Afonso'
EXEC gestao_futebol.CriaGolo 121, 79, 'Victor Andrade Santos'

EXEC gestao_futebol.CriaJogo 122,'Tondela','Maritimo'
--team_home: 'Tondela'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 122, 7, 'Yordan Osorio'
EXEC gestao_futebol.CriaGolo 122, 41, 'Luís Pedro Pinto Trabulo'
EXEC gestao_futebol.CriaGolo 122, 36, 'Fabricio Santos de Jesus'

EXEC gestao_futebol.CriaJogo 123,'Benfica','Braga'
--team_home: 'Benfica'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 123, 54, 'Bruno Miguel Semedo Varela'
EXEC gestao_futebol.CriaGolo 123, 22, 'João António Antunes Carvalho'
EXEC gestao_futebol.CriaGolo 123, 28, 'Júlio César Soares Espíndola'
EXEC gestao_futebol.CriaGolo 123, 67, 'Alejandro Grimaldo García'
EXEC gestao_futebol.CriaGolo 123, 70, 'Mile Svilar'
EXEC gestao_futebol.CriaGolo 123, 10, 'Haris Seferović'
EXEC gestao_futebol.CriaGolo 123, 44, 'André Campos Moreira'
EXEC gestao_futebol.CriaGolo 123, 80, 'Nuno Miguel Jerónimo Sequeira'

EXEC gestao_futebol.CriaJogo 124,'Vitoria de Guimaraes','Sporting CP'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 124, 70, 'Pedro Henrique Pereira da Silva'

EXEC gestao_futebol.CriaJogo 125,'Nacional','Desportivo das Chaves'
--team_home: 'Nacional'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 125, 36, 'Ricardo Jorge Pinto da Silva'
EXEC gestao_futebol.CriaGolo 125, 35, 'Gian dos Santos Martins'

EXEC gestao_futebol.CriaJogo 126,'Porto','Rio Ave'
--team_home: 'Porto'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 126, 20, 'Sérgio Miguel Relvas de Oliveira'
EXEC gestao_futebol.CriaGolo 126, 0, 'Ricardo D. Barbosa Pereira'
EXEC gestao_futebol.CriaGolo 126, 64, 'Nuno Miguel Gomes dos Santos'

EXEC gestao_futebol.CriaJogo 127,'Boavista','Vitoria de Setubal'
--team_home: 'Boavista'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 127, 77, 'Jaílton Alves Miranda'

EXEC gestao_futebol.CriaJogo 128,'Nacional','Vitoria de Guimaraes'
--team_home: 'Nacional'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 128, 79, 'Luís Miguel Vieira da Silva'

EXEC gestao_futebol.CriaJogo 129,'Portimonense','Benfica'
--team_home: 'Portimonense'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 129, 58, 'Ewerton da Silva Pereira'
EXEC gestao_futebol.CriaGolo 129, 46, 'Chidera Ezeh'

EXEC gestao_futebol.CriaJogo 130,'Rio Ave','Moreirense'
--team_home: 'Rio Ave'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 130, 42, 'Yazalde Gomes Pinto'
EXEC gestao_futebol.CriaGolo 130, 10, 'Frédéric Ferreira Maciel'
EXEC gestao_futebol.CriaGolo 130, 30, 'Rafael Eduardo Costa'

EXEC gestao_futebol.CriaJogo 131,'Santa Clara','Tondela'
--team_home: 'Santa Clara'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 131, 6, 'Thiago Cardoso'
EXEC gestao_futebol.CriaGolo 131, 2, 'Fahd Moufi'
EXEC gestao_futebol.CriaGolo 131, 24, 'Junior Pius'

EXEC gestao_futebol.CriaJogo 132,'Braga','Maritimo'
--team_home: 'Braga'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 132, 48, 'Matheus Lima Magalhães'
EXEC gestao_futebol.CriaGolo 132, 29, 'Ricardo Jorge da Luz Horta'

EXEC gestao_futebol.CriaJogo 133,'Aves','Porto'
--team_home: 'Aves'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 133, 66, 'Moreto Moro Cassamá'

EXEC gestao_futebol.CriaJogo 134,'Desportivo das Chaves','Feirense'
--team_home: 'Desportivo das Chaves'  team_away: 'Feirense' 

EXEC gestao_futebol.CriaJogo 135,'Sporting CP','Belenenses'
--team_home: 'Sporting CP'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 135, 6, 'Jonathan Silva'
EXEC gestao_futebol.CriaGolo 135, 68, 'Tobias Pereira Figueiredo'
EXEC gestao_futebol.CriaGolo 135, 69, 'Bakary Saré'

EXEC gestao_futebol.CriaJogo 136,'Maritimo','Portimonense'
--team_home: 'Maritimo'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 136, 88, 'Rodrigo Cunha Pereira de Pinho'
EXEC gestao_futebol.CriaGolo 136, 5, 'Carlos Daniel Cevada Teixeira'
EXEC gestao_futebol.CriaGolo 136, 26, 'Stanley Awurum'

EXEC gestao_futebol.CriaJogo 137,'Belenenses','Vitoria de Guimaraes'
--team_home: 'Belenenses'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 137, 82, 'Jesús Hernández'

EXEC gestao_futebol.CriaJogo 138,'Benfica','Rio Ave'
--team_home: 'Benfica'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 138, 5, 'Franco Cervi'
EXEC gestao_futebol.CriaGolo 138, 72, 'Filipe Augusto Carvalho Souza'
EXEC gestao_futebol.CriaGolo 138, 26, 'Luis Miguel Afonso Fernandes'
EXEC gestao_futebol.CriaGolo 138, 47, 'Alejandro Grimaldo García'
EXEC gestao_futebol.CriaGolo 138, 38, 'Marcos Nascimento Teixeira'
EXEC gestao_futebol.CriaGolo 138, 5, 'Yazalde Gomes Pinto'

EXEC gestao_futebol.CriaJogo 139,'Feirense','Santa Clara'
--team_home: 'Feirense'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 139, 35, 'Kódjo Alphonse'
EXEC gestao_futebol.CriaGolo 139, 73, 'Sérgio Filipe da Silva Barge'
EXEC gestao_futebol.CriaGolo 139, 4, 'Bruno Gomes Oliveira Conceição'
EXEC gestao_futebol.CriaGolo 139, 22, 'Jorman Aguilar'

EXEC gestao_futebol.CriaJogo 140,'Vitoria de Setubal','Desportivo das Chaves'
--team_home: 'Vitoria de Setubal'  team_away: 'Desportivo das Chaves' 

EXEC gestao_futebol.CriaJogo 141,'Braga','Boavista'
--team_home: 'Braga'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 141, 25, 'Lazar Rosić'

EXEC gestao_futebol.CriaJogo 142,'Moreirense','Aves'
--team_home: 'Moreirense'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 142, 34, 'João Guilherme Gonçalves de Sousa'

EXEC gestao_futebol.CriaJogo 143,'Porto','Nacional'
--team_home: 'Porto'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 143, 34, 'João Paulo Santos da Costa'
EXEC gestao_futebol.CriaGolo 143, 23, 'Maximiliano Pereira'
EXEC gestao_futebol.CriaGolo 143, 34, 'Jesús Corona'
EXEC gestao_futebol.CriaGolo 143, 36, 'Rui Jorge Farto Correia'

EXEC gestao_futebol.CriaJogo 144,'Tondela','Sporting CP'
--team_home: 'Tondela'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 144, 55, 'Heliardo Vieira da Silva'
EXEC gestao_futebol.CriaGolo 144, 33, 'Junior Pius'
EXEC gestao_futebol.CriaGolo 144, 13, 'Tobias Pereira Figueiredo'

EXEC gestao_futebol.CriaJogo 145,'Portimonense','Braga'
--team_home: 'Portimonense'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 145, 19, 'Marcel Alves Pereira'
EXEC gestao_futebol.CriaGolo 145, 89, 'Marko Bakić'

EXEC gestao_futebol.CriaJogo 146,'Aves','Feirense'
--team_home: 'Aves'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 146, 58, 'Carlos Santos Rodrigues'
EXEC gestao_futebol.CriaGolo 146, 83, 'Bruno Andrade Toledo Nascimento'

EXEC gestao_futebol.CriaJogo 147,'Vitoria de Guimaraes','Moreirense'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 147, 49, 'Héldon Augusto Almeida Ramos'

EXEC gestao_futebol.CriaJogo 148,'Santa Clara','Benfica'
--team_home: 'Santa Clara'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 148, 14, 'Lisandro López'
EXEC gestao_futebol.CriaGolo 148, 51, 'Eduardo Salvio'

EXEC gestao_futebol.CriaJogo 149,'Boavista','Maritimo'
--team_home: 'Boavista'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 149, 8, 'Fabricio Santos de Jesus'

EXEC gestao_futebol.CriaJogo 150,'Sporting CP','Porto'
--team_home: 'Sporting CP'  team_away: 'Porto' 

EXEC gestao_futebol.CriaJogo 151,'Desportivo das Chaves','Tondela'
--team_home: 'Desportivo das Chaves'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 151, 65, 'Hamdou Elhouni'
EXEC gestao_futebol.CriaGolo 151, 65, 'Pedro Miguel Pereira Silva'
EXEC gestao_futebol.CriaGolo 151, 31, 'Ricardo Baleia Janota'

EXEC gestao_futebol.CriaJogo 152,'Nacional','Belenenses'
--team_home: 'Nacional'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 152, 36, 'Bernardo Oliveira Dias'

EXEC gestao_futebol.CriaJogo 153,'Rio Ave','Vitoria de Setubal'
--team_home: 'Rio Ave'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 153, 45, 'Rui Gabriel Pinheiro Vieira'
EXEC gestao_futebol.CriaGolo 153, 58, 'Vasco Herculano Cunha Fernandes'

EXEC gestao_futebol.CriaJogo 154,'Desportivo das Chaves','Porto'
--team_home: 'Desportivo das Chaves'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 154, 15, 'Nuno André da Silva Coelho'
EXEC gestao_futebol.CriaGolo 154, 14, 'Danilo Luís Hélio Pereira'
EXEC gestao_futebol.CriaGolo 154, 70, 'Moreto Moro Cassamá'
EXEC gestao_futebol.CriaGolo 154, 3, 'José Pedro Malheiro de Sá'
EXEC gestao_futebol.CriaGolo 154, 47, 'José Diogo Dalot Teixeira'

EXEC gestao_futebol.CriaJogo 155,'Vitoria de Guimaraes','Benfica'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 155, 49, 'Raúl Jiménez'

EXEC gestao_futebol.CriaJogo 156,'Nacional','Braga'
--team_home: 'Nacional'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 156, 55, 'Rafael Henrique Assis Cardoso'
EXEC gestao_futebol.CriaGolo 156, 68, 'Bruno Viana Willemen Da Silva'
EXEC gestao_futebol.CriaGolo 156, 58, 'Matheus Lima Magalhães'

EXEC gestao_futebol.CriaJogo 157,'Belenenses','Tondela'
--team_home: 'Belenenses'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 157, 37, 'Alfredo Kulembe Ribeiro'
EXEC gestao_futebol.CriaGolo 157, 42, 'Ronei Gleison Rodrigues Reis'
EXEC gestao_futebol.CriaGolo 157, 32, 'Bruno André Freitas Monteiro'
EXEC gestao_futebol.CriaGolo 157, 7, 'Wagner Andrade Borges'

EXEC gestao_futebol.CriaJogo 158,'Santa Clara','Maritimo'
--team_home: 'Santa Clara'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 158, 89, 'Viktor Lundberg'

EXEC gestao_futebol.CriaJogo 159,'Sporting CP','Moreirense'
--team_home: 'Sporting CP'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 159, 81, 'Romain Salin'
EXEC gestao_futebol.CriaGolo 159, 64, 'Stefan Ristovski'
EXEC gestao_futebol.CriaGolo 159, 76, 'Pierre Sagna'

EXEC gestao_futebol.CriaJogo 160,'Aves','Vitoria de Setubal'
--team_home: 'Aves'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 160, 75, 'Federico Falcone'
EXEC gestao_futebol.CriaGolo 160, 50, 'Paulo Ricardo de Jesús Machado'
EXEC gestao_futebol.CriaGolo 160, 12, 'Arnold Issoko'

EXEC gestao_futebol.CriaJogo 161,'Boavista','Portimonense'
--team_home: 'Boavista'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 161, 65, 'Jadson Silva de Morais'
EXEC gestao_futebol.CriaGolo 161, 57, 'Lumor Agbenyenu'

EXEC gestao_futebol.CriaJogo 162,'Rio Ave','Feirense'
--team_home: 'Rio Ave'  team_away: 'Feirense' 

EXEC gestao_futebol.CriaJogo 163,'Feirense','Vitoria de Guimaraes'
--team_home: 'Feirense'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 163, 71, 'José Pedro Costa Leite'
EXEC gestao_futebol.CriaGolo 163, 21, 'João Miguel Coimbra Aurélio'
EXEC gestao_futebol.CriaGolo 163, 34, 'David Texeira'

EXEC gestao_futebol.CriaJogo 164,'Maritimo','Rio Ave'
--team_home: 'Maritimo'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 164, 47, 'Cássio Albuquerque Anjos'
EXEC gestao_futebol.CriaGolo 164, 6, 'Francisco Geraldes'

EXEC gestao_futebol.CriaJogo 165,'Moreirense','Nacional'
--team_home: 'Moreirense'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 165, 7, 'Rafael Eduardo Costa'
EXEC gestao_futebol.CriaGolo 165, 42, 'Frédéric Ferreira Maciel'
EXEC gestao_futebol.CriaGolo 165, 69, 'André Filipe Carneiro Leal'

EXEC gestao_futebol.CriaJogo 166,'Tondela','Aves'
--team_home: 'Tondela'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 166, 16, 'Rodrigo Alves Soares'
EXEC gestao_futebol.CriaGolo 166, 27, 'Mama Samba Baldé'

EXEC gestao_futebol.CriaJogo 167,'Benfica','Boavista'
--team_home: 'Benfica'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 167, 46, 'Chris Willock'
EXEC gestao_futebol.CriaGolo 167, 35, 'Lisandro López'
EXEC gestao_futebol.CriaGolo 167, 0, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 167, 77, 'Lisandro López'
EXEC gestao_futebol.CriaGolo 167, 30, 'Jonas Gonçalves Oliveira'
EXEC gestao_futebol.CriaGolo 167, 87, 'Rui Filipe Caetano Moura'

EXEC gestao_futebol.CriaJogo 168,'Portimonense','Desportivo das Chaves'
--team_home: 'Portimonense'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 168, 33, 'Domingos Sousa Menezes Duarte'

EXEC gestao_futebol.CriaJogo 169,'Braga','Santa Clara'
--team_home: 'Braga'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 169, 4, 'José Carlos Coentrão Marafona'

EXEC gestao_futebol.CriaJogo 170,'Porto','Belenenses'
--team_home: 'Porto'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 170, 66, 'Moreto Moro Cassamá'
EXEC gestao_futebol.CriaGolo 170, 51, 'Iker Casillas Fernández'
EXEC gestao_futebol.CriaGolo 170, 59, 'Diogo Filipe Pinto Leite'

EXEC gestao_futebol.CriaJogo 171,'Vitoria de Setubal','Sporting CP'
--team_home: 'Vitoria de Setubal'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 171, 82, 'João Rafael Brito Teixeira'
EXEC gestao_futebol.CriaGolo 171, 77, 'Douglas Franco Teixeira'

EXEC gestao_futebol.CriaJogo 172,'Rio Ave','Tondela'
--team_home: 'Rio Ave'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 172, 31, 'Bruno Martins Teles'
EXEC gestao_futebol.CriaGolo 172, 76, 'Anastasios Karamanos'
EXEC gestao_futebol.CriaGolo 172, 40, 'Jorge Samuel Fernandes'
EXEC gestao_futebol.CriaGolo 172, 16, 'Rui Pedro Coimbra Chaves'

EXEC gestao_futebol.CriaJogo 173,'Aves','Braga'
--team_home: 'Aves'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 173, 32, 'Bruno Alexandre Vieira Almeida'
EXEC gestao_futebol.CriaGolo 173, 78, 'Bruno Ricardo Valdez Wilson'

EXEC gestao_futebol.CriaJogo 174,'Boavista','Feirense'
--team_home: 'Boavista'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 174, 61, 'Vagner da Silva'
EXEC gestao_futebol.CriaGolo 174, 25, 'Eduardo José Borges Machado'

EXEC gestao_futebol.CriaJogo 175,'Desportivo das Chaves','Maritimo'
--team_home: 'Desportivo das Chaves'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 175, 22, 'Nikola Maraš'

EXEC gestao_futebol.CriaJogo 176,'Vitoria de Guimaraes','Porto'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Porto' 

EXEC gestao_futebol.CriaJogo 177,'Nacional','Vitoria de Setubal'
--team_home: 'Nacional'  team_away: 'Vitoria de Setubal' 

EXEC gestao_futebol.CriaJogo 178,'Santa Clara','Portimonense'
--team_home: 'Santa Clara'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 178, 29, 'Gustavo H. Barbosa Freire'
EXEC gestao_futebol.CriaGolo 178, 30, 'José Filipe da Silva Moreira'
EXEC gestao_futebol.CriaGolo 178, 26, 'Ricardo Abel Barbosa Ferreira'

EXEC gestao_futebol.CriaJogo 179,'Sporting CP','Benfica'
--team_home: 'Sporting CP'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 179, 46, 'Manuel David Afonso'
EXEC gestao_futebol.CriaGolo 179, 88, 'Jérémy Mathieu'
EXEC gestao_futebol.CriaGolo 179, 68, 'Gabriel Barbosa Almeida'
EXEC gestao_futebol.CriaGolo 179, 1, 'Alejandro Grimaldo García'
EXEC gestao_futebol.CriaGolo 179, 76, 'Chris Willock'
EXEC gestao_futebol.CriaGolo 179, 60, 'Chris Willock'

EXEC gestao_futebol.CriaJogo 180,'Belenenses','Moreirense'
--team_home: 'Belenenses'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 180, 7, 'Jhonatan Luiz Siqueira'

EXEC gestao_futebol.CriaJogo 181,'Moreirense','Porto'
--team_home: 'Moreirense'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 181, 71, 'Ronaldo Peña'
EXEC gestao_futebol.CriaGolo 181, 17, 'Wenderson Nascimento Galeno'

EXEC gestao_futebol.CriaJogo 182,'Maritimo','Aves'
--team_home: 'Maritimo'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 182, 38, 'Mama Samba Baldé'

EXEC gestao_futebol.CriaJogo 183,'Portimonense','Rio Ave'
--team_home: 'Portimonense'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 183, 6, 'Nuno Miguel Gomes dos Santos'

EXEC gestao_futebol.CriaJogo 184,'Tondela','Vitoria de Guimaraes'
--team_home: 'Tondela'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 184, 70, 'Yordan Osorio'

EXEC gestao_futebol.CriaJogo 185,'Benfica','Nacional'
--team_home: 'Benfica'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 185, 10, 'Andreas Samaris'
EXEC gestao_futebol.CriaGolo 185, 7, 'Franco Cervi'
EXEC gestao_futebol.CriaGolo 185, 28, 'Jardel Nivaldo Vieira'
EXEC gestao_futebol.CriaGolo 185, 15, 'Chris Willock'
EXEC gestao_futebol.CriaGolo 185, 88, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 185, 42, 'Franco Cervi'
EXEC gestao_futebol.CriaGolo 185, 89, 'Rúben Alves Dias'
EXEC gestao_futebol.CriaGolo 185, 50, 'Alejandro Grimaldo García'
EXEC gestao_futebol.CriaGolo 185, 70, 'João António Antunes Carvalho'
EXEC gestao_futebol.CriaGolo 185, 10, 'Bruno Miguel Semedo Varela'

EXEC gestao_futebol.CriaJogo 186,'Boavista','Santa Clara'
--team_home: 'Boavista'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 186, 54, 'Raphael Rossi Branco'

EXEC gestao_futebol.CriaJogo 187,'Feirense','Sporting CP'
--team_home: 'Feirense'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 187, 45, 'Christian Neiva Afonso'
EXEC gestao_futebol.CriaGolo 187, 61, 'Daniel Castelo Podence'
EXEC gestao_futebol.CriaGolo 187, 87, 'André Almeida Pinto'
EXEC gestao_futebol.CriaGolo 187, 25, 'Bruno César Zanaki'

EXEC gestao_futebol.CriaJogo 188,'Braga','Desportivo das Chaves'
--team_home: 'Braga'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 188, 44, 'Marko Bakić'
EXEC gestao_futebol.CriaGolo 188, 84, 'Fábio Santos Martins'
EXEC gestao_futebol.CriaGolo 188, 56, 'António Filipe Norinho de Carvalho'

EXEC gestao_futebol.CriaJogo 189,'Vitoria de Setubal','Belenenses'
--team_home: 'Vitoria de Setubal'  team_away: 'Belenenses' 

EXEC gestao_futebol.CriaJogo 190,'Rio Ave','Santa Clara'
--team_home: 'Rio Ave'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 190, 29, 'Óscar Barreto'
EXEC gestao_futebol.CriaGolo 190, 46, 'André Filipe Claro de Jesus'
EXEC gestao_futebol.CriaGolo 190, 63, 'Bruno Gomes Oliveira Conceição'

EXEC gestao_futebol.CriaJogo 191,'Vitoria de Guimaraes','Portimonense'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 191, 76, 'Víctor García'
EXEC gestao_futebol.CriaGolo 191, 50, 'Ghislain Konan'

EXEC gestao_futebol.CriaJogo 192,'Nacional','Feirense'
--team_home: 'Nacional'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 192, 80, 'Awer Mabil'
EXEC gestao_futebol.CriaGolo 192, 78, 'António Manuel Pereira Xavier'
EXEC gestao_futebol.CriaGolo 192, 56, 'Francisco Loureiro Afonso'
EXEC gestao_futebol.CriaGolo 192, 35, 'Bruno Araújo dos Santos'

EXEC gestao_futebol.CriaJogo 193,'Porto','Vitoria de Setubal'
--team_home: 'Porto'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 193, 62, 'Diogo Lucas Queirós'
EXEC gestao_futebol.CriaGolo 193, 79, 'Moussa Marega'

EXEC gestao_futebol.CriaJogo 194,'Belenenses','Maritimo'
--team_home: 'Belenenses'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 194, 83, 'Ricardo Jorge Oliveira Valente'

EXEC gestao_futebol.CriaJogo 195,'Desportivo das Chaves','Boavista'
--team_home: 'Desportivo das Chaves'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 195, 45, 'Paulo Sérgio Mota'
EXEC gestao_futebol.CriaGolo 195, 79, 'Jaílton Alves Miranda'

EXEC gestao_futebol.CriaJogo 196,'Moreirense','Tondela'
--team_home: 'Moreirense'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 196, 81, 'Arsénio Martins Lafuente Nunes'
EXEC gestao_futebol.CriaGolo 196, 87, 'Ernest Ohemeng'

EXEC gestao_futebol.CriaJogo 197,'Sporting CP','Braga'
--team_home: 'Sporting CP'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 197, 38, 'Pedro José Moreira da Silva'
EXEC gestao_futebol.CriaGolo 197, 74, 'João Maria Palhinha Gonçalves'
EXEC gestao_futebol.CriaGolo 197, 87, 'Bryan Ruíz'

EXEC gestao_futebol.CriaJogo 198,'Aves','Benfica'
--team_home: 'Aves'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 198, 17, 'André Gomes Magalhães Almeida'
EXEC gestao_futebol.CriaGolo 198, 51, 'Júlio César Soares Espíndola'
EXEC gestao_futebol.CriaGolo 198, 80, 'Mile Svilar'

EXEC gestao_futebol.CriaJogo 199,'Braga','Belenenses'
--team_home: 'Braga'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 199, 29, 'João Diogo Gomes de Freitas'
EXEC gestao_futebol.CriaGolo 199, 87, 'Tiago David Janeiro Caeiro'

EXEC gestao_futebol.CriaJogo 200,'Tondela','Porto'
--team_home: 'Tondela'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 200, 6, 'Diogo Filipe Pinto Leite'
EXEC gestao_futebol.CriaGolo 200, 16, 'Otávio Edmilson da Silva Monteiro'
EXEC gestao_futebol.CriaGolo 200, 28, 'José Diogo Dalot Teixeira'

EXEC gestao_futebol.CriaJogo 201,'Feirense','Moreirense'
--team_home: 'Feirense'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 201, 24, 'Luis Henrique Farinhas Taffner'
EXEC gestao_futebol.CriaGolo 201, 80, 'Ahmed Sayed'
EXEC gestao_futebol.CriaGolo 201, 39, 'Giorgi Makaridze'
EXEC gestao_futebol.CriaGolo 201, 0, 'Koffi Kouao'

EXEC gestao_futebol.CriaJogo 202,'Portimonense','Aves'
--team_home: 'Portimonense'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 202, 26, 'Stanley Awurum'
EXEC gestao_futebol.CriaGolo 202, 89, 'Cláudio Falcão Santos'

EXEC gestao_futebol.CriaJogo 203,'Vitoria de Setubal','Vitoria de Guimaraes'
--team_home: 'Vitoria de Setubal'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 203, 69, 'João Pedro Reis Amaral'
EXEC gestao_futebol.CriaGolo 203, 27, 'Junior Tallo'

EXEC gestao_futebol.CriaJogo 204,'Boavista','Rio Ave'
--team_home: 'Boavista'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 204, 53, 'Rui Filipe Caetano Moura'

EXEC gestao_futebol.CriaJogo 205,'Santa Clara','Nacional'
--team_home: 'Santa Clara'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 205, 53, 'Duarte Beirão Valente'
EXEC gestao_futebol.CriaGolo 205, 43, 'Pedro Filipe Tinoco Monteiro'

EXEC gestao_futebol.CriaJogo 206,'Benfica','Desportivo das Chaves'
--team_home: 'Benfica'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 206, 56, 'Bruno Miguel Semedo Varela'
EXEC gestao_futebol.CriaGolo 206, 56, 'Rúben Alves Dias'
EXEC gestao_futebol.CriaGolo 206, 27, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 206, 22, 'Andrija Živković'

EXEC gestao_futebol.CriaJogo 207,'Maritimo','Sporting CP'
--team_home: 'Maritimo'  team_away: 'Sporting CP' 

EXEC gestao_futebol.CriaJogo 208,'Aves','Boavista'
--team_home: 'Aves'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 208, 79, 'Adriano Facchini'
EXEC gestao_futebol.CriaGolo 208, 56, 'Cláudio Falcão Santos'

EXEC gestao_futebol.CriaJogo 209,'Moreirense','Vitoria de Setubal'
--team_home: 'Moreirense'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 209, 66, 'Alan Eduardo Schons'
EXEC gestao_futebol.CriaGolo 209, 2, 'Arnold Issoko'

EXEC gestao_futebol.CriaJogo 210,'Nacional','Tondela'
--team_home: 'Nacional'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 210, 71, 'Pedro Filipe Barbosa Moreira'
EXEC gestao_futebol.CriaGolo 210, 21, 'Bruno Daniel Castro Moreira'
EXEC gestao_futebol.CriaGolo 210, 41, 'André Manuel Nogueira Sousa'
EXEC gestao_futebol.CriaGolo 210, 35, 'Yordan Osorio'
EXEC gestao_futebol.CriaGolo 210, 60, 'Wagner Andrade Borges'

EXEC gestao_futebol.CriaJogo 211,'Porto','Benfica'
--team_home: 'Porto'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 211, 49, 'Alex Nicolao Telles'
EXEC gestao_futebol.CriaGolo 211, 81, 'André Gomes Magalhães Almeida'
EXEC gestao_futebol.CriaGolo 211, 16, 'Alejandro Grimaldo García'

EXEC gestao_futebol.CriaJogo 212,'Belenenses','Feirense'
--team_home: 'Belenenses'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 212, 30, 'Tiago David Janeiro Caeiro'
EXEC gestao_futebol.CriaGolo 212, 83, 'Jesús Hernández'
EXEC gestao_futebol.CriaGolo 212, 67, 'Vincent Sasso'
EXEC gestao_futebol.CriaGolo 212, 37, 'Gonçalo Filipe Oliveira Silva'

EXEC gestao_futebol.CriaJogo 213,'Desportivo das Chaves','Santa Clara'
--team_home: 'Desportivo das Chaves'  team_away: 'Santa Clara' 

EXEC gestao_futebol.CriaJogo 214,'Rio Ave','Braga'
--team_home: 'Rio Ave'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 214, 19, 'Judilson Mamadu Tuncara Gomes'
EXEC gestao_futebol.CriaGolo 214, 18, 'Bruno Alexandre Vieira Almeida'
EXEC gestao_futebol.CriaGolo 214, 14, 'Ricardo José Araújo Ferreira'

EXEC gestao_futebol.CriaJogo 215,'Sporting CP','Portimonense'
--team_home: 'Sporting CP'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 215, 0, 'Manuel David Afonso'
EXEC gestao_futebol.CriaGolo 215, 64, 'Bruno Miguel Borges Fernandes'
EXEC gestao_futebol.CriaGolo 215, 68, 'Alan Ruiz'
EXEC gestao_futebol.CriaGolo 215, 85, 'Wilson Miguéis Manafá Jancó'

EXEC gestao_futebol.CriaJogo 216,'Vitoria de Guimaraes','Maritimo'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 216, 52, 'Miguel Aires Fernandes Olivera'

EXEC gestao_futebol.CriaJogo 217,'Desportivo das Chaves','Rio Ave'
--team_home: 'Desportivo das Chaves'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 217, 66, 'Paulo Sérgio Mota'
EXEC gestao_futebol.CriaGolo 217, 28, 'Eliseu Mendja Soares Cassamá'

EXEC gestao_futebol.CriaJogo 218,'Boavista','Sporting CP'
--team_home: 'Boavista'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 218, 59, 'Mateus Galiano da Costa'
EXEC gestao_futebol.CriaGolo 218, 20, 'Jacinto Muondo Dala'
EXEC gestao_futebol.CriaGolo 218, 4, 'Pedro José Moreira da Silva'

EXEC gestao_futebol.CriaJogo 219,'Maritimo','Moreirense'
--team_home: 'Maritimo'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 219, 19, 'Rafael Broetto Henrique'
EXEC gestao_futebol.CriaGolo 219, 76, 'José Edgar Andrade da Costa'
EXEC gestao_futebol.CriaGolo 219, 86, 'Carlos Daniel Cevada Teixeira'
EXEC gestao_futebol.CriaGolo 219, 70, 'Giorgi Makaridze'
EXEC gestao_futebol.CriaGolo 219, 37, 'Ousmane Dramé'

EXEC gestao_futebol.CriaJogo 220,'Braga','Vitoria de Guimaraes'
--team_home: 'Braga'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 220, 44, 'Jefferson Nascimento'

EXEC gestao_futebol.CriaJogo 221,'Feirense','Porto'
--team_home: 'Feirense'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 221, 83, 'João Tavares Almeida'
EXEC gestao_futebol.CriaGolo 221, 27, 'Sérgio Miguel Relvas de Oliveira'
EXEC gestao_futebol.CriaGolo 221, 14, 'José Diogo Dalot Teixeira'

EXEC gestao_futebol.CriaJogo 222,'Portimonense','Nacional'
--team_home: 'Portimonense'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 222, 88, 'Lumor Agbenyenu'
EXEC gestao_futebol.CriaGolo 222, 71, 'Rúben Miguel Santos Fernandes'
EXEC gestao_futebol.CriaGolo 222, 1, 'Ewerton da Silva Pereira'
EXEC gestao_futebol.CriaGolo 222, 67, 'Wellington Nascimento Carvalho'
EXEC gestao_futebol.CriaGolo 222, 81, 'Marcel Alves Pereira'
EXEC gestao_futebol.CriaGolo 222, 9, 'André Filipe Ribeiro Leão'

EXEC gestao_futebol.CriaJogo 223,'Santa Clara','Aves'
--team_home: 'Santa Clara'  team_away: 'Aves' 

EXEC gestao_futebol.CriaJogo 224,'Vitoria de Setubal','Tondela'
--team_home: 'Vitoria de Setubal'  team_away: 'Tondela' 

EXEC gestao_futebol.CriaJogo 225,'Benfica','Belenenses'
--team_home: 'Benfica'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 225, 4, 'Andrija Živković'
EXEC gestao_futebol.CriaGolo 225, 58, 'Ljubomir Fejsa'
EXEC gestao_futebol.CriaGolo 225, 83, 'Miguel Jesus Rosa'
EXEC gestao_futebol.CriaGolo 225, 61, 'Juan Tomás Ortuño Martínez'

EXEC gestao_futebol.CriaJogo 226,'Sporting CP','Santa Clara'
--team_home: 'Sporting CP'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 226, 40, 'Daniel Castelo Podence'

EXEC gestao_futebol.CriaJogo 227,'Belenenses','Portimonense'
--team_home: 'Belenenses'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 227, 86, 'Bernardo Oliveira Dias'
EXEC gestao_futebol.CriaGolo 227, 28, 'Florent Hanin'
EXEC gestao_futebol.CriaGolo 227, 84, 'Gustavo Hebling de Aguiar'
EXEC gestao_futebol.CriaGolo 227, 5, 'Dener Gomes Clemente'

EXEC gestao_futebol.CriaJogo 228,'Vitoria de Guimaraes','Boavista'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 228, 57, 'Douglas Renato de Jesus'
EXEC gestao_futebol.CriaGolo 228, 5, 'Falaye Sacko'
EXEC gestao_futebol.CriaGolo 228, 89, 'João Miguel Ribeiro Vigário'
EXEC gestao_futebol.CriaGolo 228, 24, 'Ricardo Clarke'

EXEC gestao_futebol.CriaJogo 229,'Porto','Maritimo'
--team_home: 'Porto'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 229, 13, 'Vincent Aboubakar'
EXEC gestao_futebol.CriaGolo 229, 5, 'André Filipe Brás André'
EXEC gestao_futebol.CriaGolo 229, 7, 'Fabiano Ribeiro de Freitas'

EXEC gestao_futebol.CriaJogo 230,'Vitoria de Setubal','Braga'
--team_home: 'Vitoria de Setubal'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 230, 53, 'Wilson Bruno Naval Costa Eduardo'

EXEC gestao_futebol.CriaJogo 231,'Aves','Desportivo das Chaves'
--team_home: 'Aves'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 231, 27, 'Paulo Sérgio Mota'

EXEC gestao_futebol.CriaJogo 232,'Moreirense','Benfica'
--team_home: 'Moreirense'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 232, 49, 'Ljubomir Fejsa'
EXEC gestao_futebol.CriaGolo 232, 8, 'Franco Cervi'
EXEC gestao_futebol.CriaGolo 232, 19, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 232, 2, 'Rafael A. Ferreira Silva'

EXEC gestao_futebol.CriaJogo 233,'Nacional','Rio Ave'
--team_home: 'Nacional'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 233, 64, 'Hélder Tiago Pinto Moura Guedes'

EXEC gestao_futebol.CriaJogo 234,'Tondela','Feirense'
--team_home: 'Tondela'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 234, 18, 'David Dias Resende Bruno'
EXEC gestao_futebol.CriaGolo 234, 65, 'João Pedro Pereira Silva'

EXEC gestao_futebol.CriaJogo 235,'Portimonense','Moreirense'
--team_home: 'Portimonense'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 235, 74, 'Arsénio Martins Lafuente Nunes'
EXEC gestao_futebol.CriaGolo 235, 84, 'Koffi Kouao'

EXEC gestao_futebol.CriaJogo 236,'Benfica','Tondela'
--team_home: 'Benfica'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 236, 80, 'Chris Willock'

EXEC gestao_futebol.CriaJogo 237,'Desportivo das Chaves','Sporting CP'
--team_home: 'Desportivo das Chaves'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 237, 24, 'Anderson Conceição Benedito'
EXEC gestao_futebol.CriaGolo 237, 49, 'Stefan Ristovski'
EXEC gestao_futebol.CriaGolo 237, 51, 'Iuri José Picanço Medeiros'
EXEC gestao_futebol.CriaGolo 237, 34, 'Sebastián Coates'

EXEC gestao_futebol.CriaJogo 238,'Santa Clara','Vitoria de Guimaraes'
--team_home: 'Santa Clara'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 238, 52, 'Pedro Filipe Tinoco Monteiro'

EXEC gestao_futebol.CriaJogo 239,'Braga','Porto'
--team_home: 'Braga'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 239, 50, 'Mauro Silva Sousa'
EXEC gestao_futebol.CriaGolo 239, 50, 'Danilo Barbosa da Silva'
EXEC gestao_futebol.CriaGolo 239, 15, 'Yacine Brahimi'
EXEC gestao_futebol.CriaGolo 239, 71, 'Yacine Brahimi'
EXEC gestao_futebol.CriaGolo 239, 2, 'Otávio Edmilson da Silva Monteiro'

EXEC gestao_futebol.CriaJogo 240,'Boavista','Belenenses'
--team_home: 'Boavista'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 240, 53, 'João Carlos Fonseca Silva'
EXEC gestao_futebol.CriaGolo 240, 79, 'Vagner da Silva'

EXEC gestao_futebol.CriaJogo 241,'Maritimo','Nacional'
--team_home: 'Maritimo'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 241, 72, 'Eduardo Gottardi'
EXEC gestao_futebol.CriaGolo 241, 12, 'Luís Carlos Ramos Martins'
EXEC gestao_futebol.CriaGolo 241, 10, 'Fábio Diogo Agrela Ferreira'
EXEC gestao_futebol.CriaGolo 241, 56, 'Mateus da Silva'
EXEC gestao_futebol.CriaGolo 241, 33, 'Bruno Araújo dos Santos'

EXEC gestao_futebol.CriaJogo 242,'Rio Ave','Aves'
--team_home: 'Rio Ave'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 242, 61, 'Mama Samba Baldé'
EXEC gestao_futebol.CriaGolo 242, 32, 'Rodrigo Alves Soares'

EXEC gestao_futebol.CriaJogo 243,'Feirense','Vitoria de Setubal'
--team_home: 'Feirense'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 243, 35, 'André Alexandre Antunes Pedrosa'

EXEC gestao_futebol.CriaJogo 244,'Porto','Boavista'
--team_home: 'Porto'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 244, 58, 'André Filipe Brás André'
EXEC gestao_futebol.CriaGolo 244, 88, 'Sérgio Miguel Relvas de Oliveira'

EXEC gestao_futebol.CriaJogo 245,'Belenenses','Santa Clara'
--team_home: 'Belenenses'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 245, 56, 'André Geraldes de Barros'
EXEC gestao_futebol.CriaGolo 245, 57, 'Kléber Laube Pinheiro'

EXEC gestao_futebol.CriaJogo 246,'Vitoria de Guimaraes','Desportivo das Chaves'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 246, 29, 'Raphael Dias Belloli'
EXEC gestao_futebol.CriaGolo 246, 85, 'Fábio Miguel Santos Sturgeon'
EXEC gestao_futebol.CriaGolo 246, 40, 'Fábio Miguel Santos Sturgeon'
EXEC gestao_futebol.CriaGolo 246, 73, 'Miguel Aires Fernandes Olivera'

EXEC gestao_futebol.CriaJogo 247,'Moreirense','Braga'
--team_home: 'Moreirense'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 247, 19, 'Mohamed Abarhoun'

EXEC gestao_futebol.CriaJogo 248,'Nacional','Aves'
--team_home: 'Nacional'  team_away: 'Aves' 

EXEC gestao_futebol.CriaJogo 249,'Feirense','Benfica'
--team_home: 'Feirense'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 249, 89, 'Edson Rodrigues Farias'
EXEC gestao_futebol.CriaGolo 249, 69, 'Rafael A. Ferreira Silva'
EXEC gestao_futebol.CriaGolo 249, 48, 'Mile Svilar'
EXEC gestao_futebol.CriaGolo 249, 54, 'Franco Cervi'
EXEC gestao_futebol.CriaGolo 249, 40, 'Jardel Nivaldo Vieira'

EXEC gestao_futebol.CriaJogo 250,'Vitoria de Setubal','Maritimo'
--team_home: 'Vitoria de Setubal'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 250, 17, 'Tomás Martins Podstawski'

EXEC gestao_futebol.CriaJogo 251,'Sporting CP','Rio Ave'
--team_home: 'Sporting CP'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 251, 64, 'João Maria Palhinha Gonçalves'
EXEC gestao_futebol.CriaGolo 251, 64, 'Sebastián Coates'
EXEC gestao_futebol.CriaGolo 251, 33, 'Marcos Acuña'

EXEC gestao_futebol.CriaJogo 252,'Tondela','Portimonense'
--team_home: 'Tondela'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 252, 81, 'Joaquim Claude Gonçalves Araújo'
EXEC gestao_futebol.CriaGolo 252, 35, 'Bruno André Freitas Monteiro'
EXEC gestao_futebol.CriaGolo 252, 65, 'Fahd Moufi'
EXEC gestao_futebol.CriaGolo 252, 63, 'Rúben Miguel Santos Fernandes'
EXEC gestao_futebol.CriaGolo 252, 87, 'Lucas Possignolo'

EXEC gestao_futebol.CriaJogo 253,'Desportivo das Chaves','Belenenses'
--team_home: 'Desportivo das Chaves'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 253, 77, 'Matheus Fellipe Costa Pereira'
EXEC gestao_futebol.CriaGolo 253, 19, 'Wilmar Jordán'
EXEC gestao_futebol.CriaGolo 253, 20, 'João Diogo Gomes de Freitas'
EXEC gestao_futebol.CriaGolo 253, 59, 'Muriel Gustavo Becker'

EXEC gestao_futebol.CriaJogo 254,'Aves','Sporting CP'
--team_home: 'Aves'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 254, 84, 'Amilton Minervino da Silva'
EXEC gestao_futebol.CriaGolo 254, 83, 'Bruno Miguel Borges Fernandes'
EXEC gestao_futebol.CriaGolo 254, 34, 'Bruno César Zanaki'
EXEC gestao_futebol.CriaGolo 254, 13, 'Rui Pedro dos Santos Patrício'

EXEC gestao_futebol.CriaJogo 255,'Portimonense','Porto'
--team_home: 'Portimonense'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 255, 51, 'Yacine Brahimi'
EXEC gestao_futebol.CriaGolo 255, 78, 'Moussa Marega'
EXEC gestao_futebol.CriaGolo 255, 34, 'Diogo Filipe Pinto Leite'

EXEC gestao_futebol.CriaJogo 256,'Santa Clara','Moreirense'
--team_home: 'Santa Clara'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 256, 62, 'José Filipe da Silva Moreira'
EXEC gestao_futebol.CriaGolo 256, 18, 'Hichem Belkaroui'

EXEC gestao_futebol.CriaJogo 257,'Benfica','Vitoria de Setubal'
--team_home: 'Benfica'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 257, 60, 'Rúben Alves Dias'
EXEC gestao_futebol.CriaGolo 257, 22, 'Bruno Miguel Semedo Varela'
EXEC gestao_futebol.CriaGolo 257, 32, 'Gabriel Barbosa Almeida'
EXEC gestao_futebol.CriaGolo 257, 31, 'André Gomes Magalhães Almeida'
EXEC gestao_futebol.CriaGolo 257, 83, 'Arnold Issoko'
EXEC gestao_futebol.CriaGolo 257, 74, 'Sandro Rafael Veiga Cunha'

EXEC gestao_futebol.CriaJogo 258,'Boavista','Nacional'
--team_home: 'Boavista'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 258, 77, 'Aidi Fulang Xisi'

EXEC gestao_futebol.CriaJogo 259,'Maritimo','Feirense'
--team_home: 'Maritimo'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 259, 20, 'Jean Cleber Santos da Silva'
EXEC gestao_futebol.CriaGolo 259, 30, 'João Pedro da Costa Gamboa'

EXEC gestao_futebol.CriaJogo 260,'Rio Ave','Vitoria de Guimaraes'
--team_home: 'Rio Ave'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 260, 40, 'Óscar Barreto'
EXEC gestao_futebol.CriaGolo 260, 60, 'Yazalde Gomes Pinto'
EXEC gestao_futebol.CriaGolo 260, 4, 'Fábio Miguel Santos Sturgeon'

EXEC gestao_futebol.CriaJogo 261,'Braga','Tondela'
--team_home: 'Braga'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 261, 85, 'Matheus Lima Magalhães'
EXEC gestao_futebol.CriaGolo 261, 4, 'Bruno Viana Willemen Da Silva'
EXEC gestao_futebol.CriaGolo 261, 16, 'Mauro Silva Sousa'

EXEC gestao_futebol.CriaJogo 262,'Vitoria de Guimaraes','Aves'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 262, 65, 'Carlos Santos Rodrigues'
EXEC gestao_futebol.CriaGolo 262, 44, 'Pedro Miguel Silva Rocha'

EXEC gestao_futebol.CriaJogo 263,'Nacional','Sporting CP'
--team_home: 'Nacional'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 263, 86, 'Romain Salin'

EXEC gestao_futebol.CriaJogo 264,'Vitoria de Setubal','Portimonense'
--team_home: 'Vitoria de Setubal'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 264, 11, 'Vasco António Barbosa da Costa'
EXEC gestao_futebol.CriaGolo 264, 48, 'Shoya Nakajima'

EXEC gestao_futebol.CriaJogo 265,'Tondela','Boavista'
--team_home: 'Tondela'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 265, 70, 'Tyler Boyd'

EXEC gestao_futebol.CriaJogo 266,'Belenenses','Rio Ave'
--team_home: 'Belenenses'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 266, 9, 'Bruno Alexandre Marques Pereirinha'
EXEC gestao_futebol.CriaGolo 266, 11, 'Yazalde Gomes Pinto'
EXEC gestao_futebol.CriaGolo 266, 71, 'Bruno Martins Teles'
EXEC gestao_futebol.CriaGolo 266, 18, 'Victor Emanuel Araújo Ferreira'

EXEC gestao_futebol.CriaJogo 267,'Feirense','Braga'
--team_home: 'Feirense'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 267, 53, 'Marcelo Augusto Ferreira Teixeira'
EXEC gestao_futebol.CriaGolo 267, 82, 'Marko Bakić'

EXEC gestao_futebol.CriaJogo 268,'Moreirense','Desportivo das Chaves'
--team_home: 'Moreirense'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 268, 18, 'Jefferson De Jesus Santos'

EXEC gestao_futebol.CriaJogo 269,'Porto','Santa Clara'
--team_home: 'Porto'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 269, 46, 'Óliver Torres Muñoz'

EXEC gestao_futebol.CriaJogo 270,'Benfica','Maritimo'
--team_home: 'Benfica'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 270, 78, 'Paulo Jorge Pedro Lopes'
EXEC gestao_futebol.CriaGolo 270, 80, 'Martin Chrien'
EXEC gestao_futebol.CriaGolo 270, 88, 'André Gomes Magalhães Almeida'
EXEC gestao_futebol.CriaGolo 270, 2, 'Andrija Živković'
EXEC gestao_futebol.CriaGolo 270, 63, 'João António Antunes Carvalho'
EXEC gestao_futebol.CriaGolo 270, 5, 'Chris Willock'

EXEC gestao_futebol.CriaJogo 271,'Rio Ave','Porto'
--team_home: 'Rio Ave'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 271, 14, 'Marcos Nascimento Teixeira'
EXEC gestao_futebol.CriaGolo 271, 81, 'Kelechi John'
EXEC gestao_futebol.CriaGolo 271, 84, 'Maximiliano Pereira'
EXEC gestao_futebol.CriaGolo 271, 28, 'Jesús Corona'

EXEC gestao_futebol.CriaJogo 272,'Aves','Belenenses'
--team_home: 'Aves'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 272, 30, 'Diego Fortunato dos Santos Queiroz'
EXEC gestao_futebol.CriaGolo 272, 5, 'Joaquim Manuel Sampaio Silva'
EXEC gestao_futebol.CriaGolo 272, 37, 'Luis Fariña'

EXEC gestao_futebol.CriaJogo 273,'Portimonense','Feirense'
--team_home: 'Portimonense'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 273, 1, 'Oriol Rosell Argerich'

EXEC gestao_futebol.CriaJogo 274,'Santa Clara','Vitoria de Setubal'
--team_home: 'Santa Clara'  team_away: 'Vitoria de Setubal' 

EXEC gestao_futebol.CriaJogo 275,'Sporting CP','Vitoria de Guimaraes'
--team_home: 'Sporting CP'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 275, 19, 'Fábio Alexandre Silva Coentrão'
EXEC gestao_futebol.CriaGolo 275, 3, 'Tobias Pereira Figueiredo'

EXEC gestao_futebol.CriaJogo 276,'Boavista','Moreirense'
--team_home: 'Boavista'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 276, 15, 'Nuno Henrique Gonçalves Nogueira'
EXEC gestao_futebol.CriaGolo 276, 79, 'Leonardo Ruíz'
EXEC gestao_futebol.CriaGolo 276, 72, 'Raphael Rossi Branco'
EXEC gestao_futebol.CriaGolo 276, 11, 'Jhonder Cádiz'

EXEC gestao_futebol.CriaJogo 277,'Desportivo das Chaves','Nacional'
--team_home: 'Desportivo das Chaves'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 277, 34, 'Pedro Miguel Pereira Silva'
EXEC gestao_futebol.CriaGolo 277, 64, 'Jeferson Fernandes Macedo'
EXEC gestao_futebol.CriaGolo 277, 40, 'Davidson da Luz Pereira'
EXEC gestao_futebol.CriaGolo 277, 16, 'Renan Bardini Bressan'
EXEC gestao_futebol.CriaGolo 277, 18, 'Pedro Filipe Barbosa Moreira'

EXEC gestao_futebol.CriaJogo 278,'Maritimo','Tondela'
--team_home: 'Maritimo'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 278, 32, 'Pablo Renan dos Santos'
EXEC gestao_futebol.CriaGolo 278, 7, 'Fabricio Santos de Jesus'

EXEC gestao_futebol.CriaJogo 279,'Braga','Benfica'
--team_home: 'Braga'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 279, 39, 'João Carlos Vilaça Teixeira'
EXEC gestao_futebol.CriaGolo 279, 87, 'Diogo António Cupido Gonçalves'
EXEC gestao_futebol.CriaGolo 279, 25, 'Mile Svilar'
EXEC gestao_futebol.CriaGolo 279, 55, 'Eduardo Salvio'
EXEC gestao_futebol.CriaGolo 279, 13, 'Raúl Jiménez'

EXEC gestao_futebol.CriaJogo 280,'Moreirense','Rio Ave'
--team_home: 'Moreirense'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 280, 67, 'Alfa Semedo Esteves'
EXEC gestao_futebol.CriaGolo 280, 76, 'Carlos Reinaldo Moreira Alves'
EXEC gestao_futebol.CriaGolo 280, 37, 'Yazalde Gomes Pinto'

EXEC gestao_futebol.CriaJogo 281,'Benfica','Portimonense'
--team_home: 'Benfica'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 281, 49, 'Jonas Gonçalves Oliveira'
EXEC gestao_futebol.CriaGolo 281, 2, 'Rúben Alves Dias'
EXEC gestao_futebol.CriaGolo 281, 76, 'André Gomes Magalhães Almeida'
EXEC gestao_futebol.CriaGolo 281, 0, 'Filipe Augusto Carvalho Souza'
EXEC gestao_futebol.CriaGolo 281, 83, 'Martin Chrien'
EXEC gestao_futebol.CriaGolo 281, 36, 'Ewerton da Silva Pereira'

EXEC gestao_futebol.CriaJogo 282,'Feirense','Desportivo das Chaves'
--team_home: 'Feirense'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 282, 64, 'Peter Etebo'
EXEC gestao_futebol.CriaGolo 282, 79, 'Luis Henrique Farinhas Taffner'
EXEC gestao_futebol.CriaGolo 282, 18, 'Luis Henrique Farinhas Taffner'
EXEC gestao_futebol.CriaGolo 282, 21, 'Kódjo Alphonse'
EXEC gestao_futebol.CriaGolo 282, 65, 'Matheus Fellipe Costa Pereira'
EXEC gestao_futebol.CriaGolo 282, 15, 'Jeferson Fernandes Macedo'
EXEC gestao_futebol.CriaGolo 282, 57, 'Matheus Fellipe Costa Pereira'
EXEC gestao_futebol.CriaGolo 282, 7, 'Domingos Sousa Menezes Duarte'

EXEC gestao_futebol.CriaJogo 283,'Maritimo','Braga'
--team_home: 'Maritimo'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 283, 0, 'Luís Carlos Ramos Martins'

EXEC gestao_futebol.CriaJogo 284,'Porto','Aves'
--team_home: 'Porto'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 284, 50, 'Diogo Filipe Pinto Leite'
EXEC gestao_futebol.CriaGolo 284, 27, 'Iván Marcano Sierra'
EXEC gestao_futebol.CriaGolo 284, 64, 'Óliver Torres Muñoz'
EXEC gestao_futebol.CriaGolo 284, 70, 'Alberto Bueno Calvo'

EXEC gestao_futebol.CriaJogo 285,'Belenenses','Sporting CP'
--team_home: 'Belenenses'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 285, 23, 'Jesús Hernández'
EXEC gestao_futebol.CriaGolo 285, 80, 'Marcos Acuña'
EXEC gestao_futebol.CriaGolo 285, 85, 'Iuri José Picanço Medeiros'
EXEC gestao_futebol.CriaGolo 285, 62, 'Seydou Doumbia'
EXEC gestao_futebol.CriaGolo 285, 87, 'Sebastián Coates'
EXEC gestao_futebol.CriaGolo 285, 22, 'Jacinto Muondo Dala'
EXEC gestao_futebol.CriaGolo 285, 68, 'Gelson Dany Batalha Martins'
EXEC gestao_futebol.CriaGolo 285, 5, 'Jonathan Silva'
EXEC gestao_futebol.CriaGolo 285, 67, 'Marcos Acuña'

EXEC gestao_futebol.CriaJogo 286,'Vitoria de Guimaraes','Nacional'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 286, 41, 'Junior Tallo'
EXEC gestao_futebol.CriaGolo 286, 32, 'Fábio Miguel Santos Sturgeon'
EXEC gestao_futebol.CriaGolo 286, 1, 'Rafael Garcia Tonioli Defendi'
EXEC gestao_futebol.CriaGolo 286, 81, 'André Filipe Carneiro Leal'

EXEC gestao_futebol.CriaJogo 287,'Tondela','Santa Clara'
--team_home: 'Tondela'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 287, 82, 'Junior Pius'
EXEC gestao_futebol.CriaGolo 287, 71, 'Rafik Halliche'
EXEC gestao_futebol.CriaGolo 287, 66, 'Luís Carlos Santos Ribeiro'
EXEC gestao_futebol.CriaGolo 287, 39, 'Bruno Gomes Oliveira Conceição'

EXEC gestao_futebol.CriaJogo 288,'Vitoria de Setubal','Boavista'
--team_home: 'Vitoria de Setubal'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 288, 86, 'Vagner da Silva'
EXEC gestao_futebol.CriaGolo 288, 51, 'Stéphane Sparagna'
EXEC gestao_futebol.CriaGolo 288, 85, 'Yusupha Njie'

EXEC gestao_futebol.CriaJogo 289,'Aves','Moreirense'
--team_home: 'Aves'  team_away: 'Moreirense' 
EXEC gestao_futebol.CriaGolo 289, 65, 'Pierre Sagna'

EXEC gestao_futebol.CriaJogo 290,'Boavista','Braga'
--team_home: 'Boavista'  team_away: 'Braga' 
EXEC gestao_futebol.CriaGolo 290, 1, 'Idrissa Mandiang'
EXEC gestao_futebol.CriaGolo 290, 18, 'Tiago Manuel Oliveira Mesquita'
EXEC gestao_futebol.CriaGolo 290, 22, 'Yusupha Njie'
EXEC gestao_futebol.CriaGolo 290, 36, 'Mateus Galiano da Costa'
EXEC gestao_futebol.CriaGolo 290, 32, 'Nuno Miguel Jerónimo Sequeira'
EXEC gestao_futebol.CriaGolo 290, 12, 'Ricardo Sousa Esgaio'

EXEC gestao_futebol.CriaJogo 291,'Portimonense','Maritimo'
--team_home: 'Portimonense'  team_away: 'Maritimo' 
EXEC gestao_futebol.CriaGolo 291, 26, 'Jorge Costa Pires'
EXEC gestao_futebol.CriaGolo 291, 81, 'Marcel Alves Pereira'
EXEC gestao_futebol.CriaGolo 291, 26, 'Wilson Miguéis Manafá Jancó'
EXEC gestao_futebol.CriaGolo 291, 32, 'Cristiano Castro Gomes'
EXEC gestao_futebol.CriaGolo 291, 30, 'Fábio José Ferreira Pacheco'

EXEC gestao_futebol.CriaJogo 292,'Santa Clara','Feirense'
--team_home: 'Santa Clara'  team_away: 'Feirense' 
EXEC gestao_futebol.CriaGolo 292, 78, 'Victor Andrade Santos'
EXEC gestao_futebol.CriaGolo 292, 38, 'Allano Brendon de Souza Lima'
EXEC gestao_futebol.CriaGolo 292, 40, 'Kléber Laube Pinheiro'
EXEC gestao_futebol.CriaGolo 292, 65, 'Kléber Laube Pinheiro'
EXEC gestao_futebol.CriaGolo 292, 61, 'Hugo André Rodrigues Seco'
EXEC gestao_futebol.CriaGolo 292, 62, 'Luís Carlos Rocha Rodrigues'
EXEC gestao_futebol.CriaGolo 292, 48, 'Alex Kakuba'
EXEC gestao_futebol.CriaGolo 292, 31, 'Luís Miguel Vieira Machado'

EXEC gestao_futebol.CriaJogo 293,'Sporting CP','Tondela'
--team_home: 'Sporting CP'  team_away: 'Tondela' 
EXEC gestao_futebol.CriaGolo 293, 64, 'Rodrigo Battaglia'
EXEC gestao_futebol.CriaGolo 293, 54, 'Fahd Moufi'

EXEC gestao_futebol.CriaJogo 294,'Desportivo das Chaves','Vitoria de Setubal'
--team_home: 'Desportivo das Chaves'  team_away: 'Vitoria de Setubal' 
EXEC gestao_futebol.CriaGolo 294, 55, 'Ricardo Jorge Novo Nunes'
EXEC gestao_futebol.CriaGolo 294, 24, 'João Pedro Reis Amaral'
EXEC gestao_futebol.CriaGolo 294, 3, 'José Vítor Moreira Semedo'

EXEC gestao_futebol.CriaJogo 295,'Vitoria de Guimaraes','Belenenses'
--team_home: 'Vitoria de Guimaraes'  team_away: 'Belenenses' 
EXEC gestao_futebol.CriaGolo 295, 55, 'Francisco Simões Rodrigues'
EXEC gestao_futebol.CriaGolo 295, 46, 'Miguel Ângelo Moreira Magalhães'
EXEC gestao_futebol.CriaGolo 295, 43, 'Raphael Dias Belloli'
EXEC gestao_futebol.CriaGolo 295, 41, 'Francisco Simões Rodrigues'
EXEC gestao_futebol.CriaGolo 295, 6, 'Dénis Paulo Duarte'
EXEC gestao_futebol.CriaGolo 295, 37, 'Carlos Filipe Fonseca Chaby'

EXEC gestao_futebol.CriaJogo 296,'Nacional','Porto'
--team_home: 'Nacional'  team_away: 'Porto' 
EXEC gestao_futebol.CriaGolo 296, 33, 'Yacine Brahimi'
EXEC gestao_futebol.CriaGolo 296, 66, 'Miguel Layún'
EXEC gestao_futebol.CriaGolo 296, 72, 'Felipe Augusto de Almeida Monteiro'
EXEC gestao_futebol.CriaGolo 296, 38, 'Maximiliano Pereira'

EXEC gestao_futebol.CriaJogo 297,'Rio Ave','Benfica'
--team_home: 'Rio Ave'  team_away: 'Benfica' 
EXEC gestao_futebol.CriaGolo 297, 65, 'Marcelo dos Santos Ferreira'
EXEC gestao_futebol.CriaGolo 297, 5, 'Marcos Nascimento Teixeira'
EXEC gestao_futebol.CriaGolo 297, 51, 'Raúl Jiménez'
EXEC gestao_futebol.CriaGolo 297, 57, 'Andreas Samaris'
EXEC gestao_futebol.CriaGolo 297, 69, 'André Gomes Magalhães Almeida'

EXEC gestao_futebol.CriaJogo 298,'Belenenses','Nacional'
--team_home: 'Belenenses'  team_away: 'Nacional' 
EXEC gestao_futebol.CriaGolo 298, 2, 'Tiago David Janeiro Caeiro'
EXEC gestao_futebol.CriaGolo 298, 60, 'José Cleylton Santos'
EXEC gestao_futebol.CriaGolo 298, 0, 'Nuno Miguel Adro Tomás'

EXEC gestao_futebol.CriaJogo 299,'Braga','Portimonense'
--team_home: 'Braga'  team_away: 'Portimonense' 
EXEC gestao_futebol.CriaGolo 299, 26, 'Ricardo Jorge da Luz Horta'
EXEC gestao_futebol.CriaGolo 299, 65, 'Marko Bakić'

EXEC gestao_futebol.CriaJogo 300,'Benfica','Santa Clara'
--team_home: 'Benfica'  team_away: 'Santa Clara' 
EXEC gestao_futebol.CriaGolo 300, 78, 'Eduardo Salvio'
EXEC gestao_futebol.CriaGolo 300, 43, 'Mile Svilar'
EXEC gestao_futebol.CriaGolo 300, 81, 'Anderson Luís da Silva'
EXEC gestao_futebol.CriaGolo 300, 9, 'Eduardo Salvio'
EXEC gestao_futebol.CriaGolo 300, 70, 'José Filipe da Silva Moreira'

EXEC gestao_futebol.CriaJogo 301,'Feirense','Aves'
--team_home: 'Feirense'  team_away: 'Aves' 
EXEC gestao_futebol.CriaGolo 301, 12, 'Gustavo Ermel'
EXEC gestao_futebol.CriaGolo 301, 84, 'José Valencia'
EXEC gestao_futebol.CriaGolo 301, 67, 'Bruno Manuel Araújo Braga'

EXEC gestao_futebol.CriaJogo 302,'Maritimo','Boavista'
--team_home: 'Maritimo'  team_away: 'Boavista' 
EXEC gestao_futebol.CriaGolo 302, 36, 'Idrissa Mandiang'

EXEC gestao_futebol.CriaJogo 303,'Porto','Sporting CP'
--team_home: 'Porto'  team_away: 'Sporting CP' 
EXEC gestao_futebol.CriaGolo 303, 41, 'Sérgio Miguel Relvas de Oliveira'
EXEC gestao_futebol.CriaGolo 303, 84, 'Diego Reyes'
EXEC gestao_futebol.CriaGolo 303, 51, 'Iuri José Picanço Medeiros'

EXEC gestao_futebol.CriaJogo 304,'Vitoria de Setubal','Rio Ave'
--team_home: 'Vitoria de Setubal'  team_away: 'Rio Ave' 
EXEC gestao_futebol.CriaGolo 304, 30, 'Patrick De Oliveira Vieira'
EXEC gestao_futebol.CriaGolo 304, 64, 'Yuri Oliveira Ribeiro'
EXEC gestao_futebol.CriaGolo 304, 63, 'Pedro Manuel da Silva Moreira'
EXEC gestao_futebol.CriaGolo 304, 8, 'Eliseu Mendja Soares Cassamá'

EXEC gestao_futebol.CriaJogo 305,'Moreirense','Vitoria de Guimaraes'
--team_home: 'Moreirense'  team_away: 'Vitoria de Guimaraes' 
EXEC gestao_futebol.CriaGolo 305, 69, 'Bilel Aouacheria'
EXEC gestao_futebol.CriaGolo 305, 19, 'Raphael Dias Belloli'
EXEC gestao_futebol.CriaGolo 305, 39, 'Ghislain Konan'
EXEC gestao_futebol.CriaGolo 305, 3, 'Ghislain Konan'

EXEC gestao_futebol.CriaJogo 306,'Tondela','Desportivo das Chaves'
--team_home: 'Tondela'  team_away: 'Desportivo das Chaves' 
EXEC gestao_futebol.CriaGolo 306, 85, 'Wagner Andrade Borges'
EXEC gestao_futebol.CriaGolo 306, 67, 'Heliardo Vieira da Silva'
EXEC gestao_futebol.CriaGolo 306, 7, 'Wagner Andrade Borges'
EXEC gestao_futebol.CriaGolo 306, 84, 'Ricardo Baleia Janota'
EXEC gestao_futebol.CriaGolo 306, 49, 'Tyler Boyd'
EXEC gestao_futebol.CriaGolo 306, 64, 'Matheus Fellipe Costa Pereira'
EXEC gestao_futebol.CriaGolo 306, 19, 'Anderson Conceição Benedito'
SET IDENTITY_INSERT gestao_futebol.jogo OFF
